slangs = {
'awsm':'awesome',
"a/s/l":"age/sex/location",
"a/s/l/p":"age, sex, location, picture",
"a2d":"agree to disagree",
"a2t":"addicted to texting",
"a3":"anyplace, anywhere, anytime",
"a7x":"avenged sevenfold",
"aaf":"as a friend",
"aaf":"always and forever",
"aak":"asleep at keyboard",
"aak":"alive and kicking",
"aamof":"as a matter of fact",
"aap":"always a pleasure",
"aar":"at any rate",
"aar8":"at any rate",
"aarping":"elderly person complaining repeatedly",
"aas":"alive and smiling",
"aatk":"always at the keyboard",
"aawc":"after awhile crocodile",
"aayf":"as always, your friend",
"abbrev":"abbreviation",
"abcp":"a bad computer professional",
"abd":"already been done",
"abt":"about",
"abt2":"about to",
"ac":"air conditioning",
"acc":"anyone can come",
"acd":"alt-control-delete",
"ace":"solo winner",
"ack":"acknowledged",
"ad":"attack damage",
"adad":"another day another dollar",
"adam":"all draft all mid",
"adbb":"all done, bye-bye",
"adc":"attack damage carry",
"add":"address",
"adds":"additional mobs",
"addy":"address",
"adih":"another day in hell",
"adip":"another day in paradise",
"adm":"ay dios mio",
"admin":"administrator",
"adn":"any day now",
"adorbs":"adorable",
"adpic":"always dependably politically incorrect",
"ads":"aiming down sight",
"ae":"area of effect",
"aeap":"as early as possible",
"af":"aggression factor",
"afaiaa":"as far as i am aware",
"afaiac":"as far as i am concerned",
"afaic":"as far as i'm concerned",
"afaics":"as far as i can see",
"afaict":"as far as i can tell",
"afaik":"as far as i know",
"afair":"as far as i remember",
"afap":"as fast as possible",
"afayc":"as far as you're concerned",
"afb":"away from brain",
"afc":"american football conference",
"afc":"away from computer",
"afc":"away from controller",
"afda":"a few days ago",
"afdb":"a few days back",
"afhv":"america's funniest home videos",
"afi":"a fire inside",
"afj":"april fools' joke",
"afk":"away from keyboard",
"afn":"all for now",
"afpoe":"a fresh pair of eyes",
"afro":"natural bush-like hairstyle",
"afu":"all fucked up",
"afv":"america's funniest videos",
"afwiw":"anyway, for what it's worth",
"aggro":"aggression",
"agi":"agility",
"agl":"angel",
"ah":"at home",
"ah":"auction house",
"ahfy":"always here for you",
"ai":"as if",
"ai":"artificial intelligence",
"ai":"all in",
"aight":"alright",
"aiic":"as if i care",
"aim":"aol instant messenger",
"aimb":"as i mentioned before",
"aimbot":"automatic aiming bot",
"aime":"as i mentioned earlier",
"aimp":"always in my prayers",
"aip":"agreement in principle",
"aipf":"all in preflop",
"airhead":"stupid",
"aisb":"as i said before",
"aise":"as i said earlier",
"aisi":"as i see it",
"aiui":"as i understand it",
"aj":"absolute jerk",
"ak":"ak-47",
"aka":"also known as",
"al":"american league",
"alap":"as long as possible",
"alap":"as late as possible",
"alg":"ain't life grand",
"alol":"actually laughing out loud",
"alt":"a lot",
"alt":"alternate character",
"alw":"ain't life wonderful",
"ama":"ask me anything",
"amap":"as much as possible",
"amazeballs":"amazing",
"amazn":"amazing",
"ambl":"all my boundless love",
"ambw":"all my best wishes",
"amf":"adios my friend",
"amg":"ah my gosh",
"aml":"all my love",
"ammo":"ammunition",
"amp":"to be loud and angry",
"amp":"adventure multiplayer",
"amped":"pumped up",
"ams":"ask me something",
"anfscd":"and now for something completely different",
"anon":"anonymous",
"antm":"america's next top model",
"anuda":"another",
"aoas":"all of a sudden",
"aoc":"available on cell",
"aoe":"area of effect",
"aoi":"ass on ice",
"aomm":"always on my mind",
"aon":"all or nothing",
"aon":"as of now",
"aon":"apropos of nothing",
"aota":"all of the above",
"aoyp":"angel on your pillow",
"ap":"ability power",
"ap":"attached parenting",
"ap":"attack power",
"apac":"all praise and credit",
"apc":"a perfect circle",
"apm":"actions per minute",
"app":"application",
"app":"appreciate",
"ar":"assault rifle",
"aram":"all random all mid",
"arp":"armor penetration",
"arpen":"armor penetration",
"asaic":"as soon as i can",
"asaik":"as soon as i know",
"asap":"as soon as possible",
"asat":"as simple as that",
"asayc":"as soon as you can",
"asaygt":"as soon as you get this",
"asl":"age, sex, location",
"aslp":"age, sex, location, picture",
"asp":"after show party",
"asyc":"as soon as you can",
"atb":"all the best",
"atm":"at the moment",
"atm":"automated teller machine",
"atpm":"about to pee myself",
"atsl":"along the same lines",
"atst":"at the same time",
"att":"all the time",
"attaboy":"good job",
"attagirl":"good job",
"attn":"attention",
"attny":"attorney",
"attt":"ain't that the truth",
"attwaction":"attraction to a twitter user",
"attwicted":"addicted to twitter",
"atw":"all the way",
"atys":"anything you say",
"aut":"are you there",
"automagically":"magically automatic",
"awa":"as well as",
"awc":"after awhile crocodile",
"awesomesauce":"super awesome",
"awhfy":"are we having fun yet?",
"awks":"awkward",
"awl":"always with love",
"awltp":"avoiding work like the plague",
"awol":"absent while online",
"awt":"at what time",
"awty":"are we there yet?",
"ayaotd":"are you afraid of the dark?",
"aybabtu":"all your base are belong to us",
"ayc":"are you coming?",
"aydy":"are you done yet?",
"ayec":"at your earliest convenience",
"ayfr":"are you for real?",
"ayft":"are you free today?",
"ayk":"as you know",
"aykm":"are you kidding me?",
"ayor":"at your own risk",
"aypi":"and your point is?",
"ays":"are you serious?",
"aysos":"are you stupid or something?",
"ayt":"are you there?",
"aytmtb":"and you're telling me this because",
"ayw":"as you wish",
"ayw":"as you were",
"aywk":"as you well know",
"azm":"awesome",
"azn":"asian",
"azz":"ass",
"b":"be",
"b&e":"breaking and entering",
"b&f":"back and forth",
"b&w":"black and white",
"b-day":"birthday",
"b/c":"because",
"b/f":"boyfriend",
"b/f":"brain fart",
"b/r":"bathroom",
"b/w":"between",
"b1g1":"buy one, get one",
"b2w":"back to work",
"b4":"before",
"b4n":"bye for now",
"b4u":"before you",
"b@u":"back at you",
"ba":"bad ass",
"ba":"bitch ass",
"baa":"broad agency announcement",
"babe":"attractive person",
"bac":"bad ass chick",
"bac":"back at computer",
"bae":"babe",
"bae":"before anyone else",
"bae":"before anything else",
"baf":"bring a friend",
"bafo":"best and final offer",
"bai":"bye",
"baic":"boy am i confused",
"bak":"back at keyboard",
"baller":"cool person",
"bam":"below average mentality",
"bamf":"bad ass mother fucking",
"bao":"be aware of",
"barcraft":"bar gathering for starcraft",
"basor":"breathing a sigh of relief",
"bau":"business as usual",
"bb":"bright blessings",
"bb":"breaking bad",
"bb":"big blind",
"bb":"blessed be",
"bb":"be back",
"bb":"bye bye",
"bb/100":"big bets per 100 hands",
"bb4n":"bye bye for now",
"bbb":"boring beyond belief",
"bbfn":"bye-bye for now",
"bbiab":"be back in a bit",
"bbiaf":"be back in a few",
"bbiam":"be back in a minute",
"bbias":"be back in a second",
"bbl":"be back later",
"bbm":"brains by mattel",
"bbml":"be back much later",
"bbn":"bye bye now",
"bbol":"be back on later",
"bbq":"barbecue",
"bbs":"bulletin board system",
"bbs":"be back soon",
"bbss":"be back soon sweetie",
"bbt":"be back tomorrow",
"bbw":"be back whenever",
"bbw":"big beautiful women",
"bbw":"big black women",
"bbwl":"be back way later",
"bc":"because",
"bc":"be cool",
"bc":"burning crusade",
"bc":"back cover",
"bcbg":"bon chic bon genre",
"bcc":"blind carbon copy",
"bcnu":"be seein' you",
"bco":"big crush on",
"bcos":"because",
"bcoy":"big crush on you",
"bcoz":"because",
"bcz":"because",
"bd":"blu-ray",
"bd":"backdoor",
"bd":"big deal",
"bd":"birthday",
"bday":"birthday",
"bdu":"brain dead user",
"beamer":"bmw vehicle",
"beef":"bothering problem",
"beemer":"bmw vehicle",
"belf":"blood elf",
"bennifer":"ben and jennifer",
"bestie":"best friend",
"bf":"boyfriend",
"bf":"brain fart",
"bf":"b.f. sword",
"bf2":"battlefield 2",
"bfaw":"best friend at work",
"bfd":"big freakin' deal",
"bff":"best friends forever",
"bff4l":"best friends forever for life",
"bffae":"best friends forever and ever",
"bffe":"best friends forever",
"bffl":"best friend for life",
"bfflab":"best friend for life and beyond",
"bffm":"best friends forevermore",
"bffn":"best friend for now",
"bfg":"big friggin' gun",
"bfh":"bitch from hell",
"bfk":"big fat kiss",
"bfn":"bye for now",
"bfn":"big fat negative",
"bfp":"big fat positive",
"bfr":"big freakin' rock",
"bftd":"best friends till death",
"bfu":"bezny franta uzivatel",
"bfu":"brain free user",
"bg":"battleground",
"bg":"big grin",
"bg":"bad game",
"bg":"blood glucose",
"bgf":"best guy friend",
"bgr":"boy girl relationship",
"bh":"better half",
"bh":"bloody hell",
"bh@":"be home at",
"bhl8":"be home late",
"bhs":"be home soon",
"bi5":"back in five",
"biab":"back in a bit",
"biam":"back in a minute",
"bibi":"bye bye",
"bic":"butt in chair",
"biffles":"best friends for life",
"bil":"brother-in-law",
"bil":"boss is listening",
"bimbo":"dumb and attractive female",
"bin":"buy it now",
"bio":"bathroom",
"bio":"bring it on",
"bio":"biological units",
"bioball":"biological unit group",
"biome":"minecraft region",
"bion":"believe it or not",
"bioya":"blow it out your ass",
"bis":"best in slot",
"bisly":"but i still love you",
"bitmt":"but in the meantime",
"bits":"back in the saddle",
"biz":"business",
"bk":"back",
"bk":"burger king",
"bka":"better known as",
"bl":"buddy list",
"bl":"belly laughing",
"blinkie":"coupon dispenser machine",
"blizz":"blizzard",
"blops":"black ops",
"bltn":"better late than never",
"bluf":"bottom line up front",
"blvmot":"believe me on that",
"bm":"bad manner",
"bm":"bite me",
"bma":"best mates always",
"bmbo":"blow my brains out",
"bme":"based on my experience",
"bmgwl":"busting my gut with laughter",
"bmw":"boy meets world",
"bmw":"bayerische motoren werke",
"bn":"bad news",
"bnib":"brand new in box",
"bno":"boys night out",
"bnr":"but not really",
"bo":"body odor",
"bo":"build order",
"bo":"back off",
"bo3":"best of three",
"bo5":"best of five",
"boc":"butt on chair",
"bod":"body",
"boe":"bind on equip",
"bogo":"buy one, get one",
"bohica":"bend over here it comes again",
"bol":"be on later",
"boo":"term of endearment",
"boomkin":"moonkin druid",
"booms":"bored out of my skull",
"boomstick":"doom shotgun",
"boosting":"unfair level boosting",
"bootsie":"boring person",
"bootylicious":"attractive female's rear",
"booyah":"hooray",
"booze":"alcohol",
"bop":"bind on pickup",
"bos":"brat over shoulder",
"botb":"back of the book",
"botd":"benefit of the doubt",
"bout":"about",
"boyds":"back off you dipstick",
"bp":"blue pilling",
"br":"blu-ray",
"br":"bank roll",
"br":"bathroom",
"br":"best regards",
"br":"buyer's remorse",
"brah":"bro",
"brangelina":"brad and angelina",
"brb":"bathroom break",
"brb":"be right back",
"brbrb":"bathroom, be right back",
"brbs":"be right back soon",
"brd":"bored",
"brez":"battle resurrection",
"brh":"be right here",
"bridezilla":"godzilla bride",
"brillz":"brilliant",
"bro":"brother",
"bro":"be right over",
"brolling":"james bond trolling",
"bromance":"a non-sexual friendship between two or more males",
"brony":"male viewer of my little pony",
"broseph":"male friend",
"brotastic":"great male bonding time",
"brrrb":"be rrright back",
"brt":"be right there",
"bs":"blood sugar",
"bs":"bull suck",
"bsb":"backstreet boys",
"bsod":"blue screen of death",
"bst":"but seriously though",
"bstd":"busted",
"bsts":"better safe than sorry",
"bt":"bittorrent",
"bt":"bad taste",
"bt":"bluetooth",
"bta":"but then again",
"btaim":"be that as it may",
"btchf":"bye, take care, have fun",
"btd":"bored to death",
"btdt":"been there, done that",
"btho":"back the heck off",
"bthrm":"bathroom",
"bthu":"back the heck up",
"btk":"back to keyboard",
"btm":"bite me",
"btn":"better than nothing",
"btobs":"be there or be square",
"btsoom":"beats the shizzle out of me",
"btw":"by the way",
"btwitiailwu":"by the way, i think i am in love with you",
"btwitiailwy":"by the way, i think i am in love with you",
"btwitiilwy":"by the way, i think i'm in love with you",
"btwitily":"by the way, i think i love you",
"btwn":"between",
"btyc":"better than you can",
"bu&i":"between you and i",
"bubi":"goodbye",
"buck":"dollar",
"budder":"gold",
"buf":"big ugly fellow",
"buf":"big, ugly, fat",
"buff":"strengthen",
"buhbye":"bye",
"bump":"forum post message bump",
"bunnies":"first-person shooter jumping",
"bup":"backup plan",
"butterface":"unattractive female face",
"bw":"best wishes",
"bw":"be well",
"bwbr":"brunette with blonde roots",
"bwdik":"but what do i know",
"bwg":"big wide grin",
"bwl":"bursting with laughter",
"bwq":"buzzword quotient",
"bwthdik":"but what the heck do i know",
"bwtm":"but wait, there's more",
"byh":"bless your heart",
"byki":"before you know it",
"bykt":"but you knew that",
"byob":"bring your own beer",
"byod":"bring your own device",
"byodkm":"bring your own display, keyboard, and mouse",
"bytm":"better you than me",
"bz":"busy",
"c":"see",
"c&g":"chuckle and grin",
"c-p":"sleepy",
"c/o":"care of",
"c/p":"crossposting",
"c/s":"change subject",
"c2c":"cam to cam",
"c4n":"ciao for now",
"c9":"parent in room",
"cab":"taxi",
"cac":"cool as a cucumber",
"cad":"control-alt-delete",
"camping":"holding position",
"cas":"clothing acquisition syndrome",
"cata":"cataclysm",
"cb":"chris brown",
"cbf":"can't be bothered",
"cc":"command center",
"cc":"credit card",
"cc":"crowd control",
"cc":"i understand",
"cc":"carbon copy",
"ccg":"collectible card game",
"ccr":"creedence clearwater revival",
"cd":"cooldown",
"cd9":"parents are watching",
"cd99":"parents are no longer watching",
"cdiwy":"couldn't do it without you",
"cdr":"cooldown reduction",
"ceebs":"can't be bothered",
"cf":"cluster fuck",
"cf":"coffee freak",
"cfs":"care for a secret?",
"cfv":"call for votes",
"cg":"computer graphics",
"cgm":"continuous glucose monitoring",
"cgms":"continuous glucose monitoring system",
"char":"character",
"chargelot":"charge zealot",
"cheerio":"goodbye",
"cheesy":"corny",
"chibi":"miniature character",
"chillax":"chill and relax",
"chingo":"chat lingo",
"chirp":"diss",
"chiver":"male who likes thechive",
"chivette":"female who likes thechive",
"chk":"check",
"chln":"chilling",
"choob":"skilled player who intentionally plays badly",
"chrismukkah":"christmas and hanukkah",
"chu":"you",
"churrin":"children",
"chx":"chickens",
"cia":"see ya",
"cicu":"can i see you?",
"cicyh":"can i copy your homework",
"cicyhw":"can i copy your homework",
"cid":"consider it done",
"cil":"check in later",
"cip":"customer initiated payment",
"cip":"cell it please",
"cis":"consumer information service",
"cld":"could",
"clk":"click",
"clm":"career limiting move",
"clowning":"joking",
"cm":"call me",
"cmb":"call me back",
"cme":"checking my e-mail",
"cmfwic":"chief mo fo of who's in charge",
"cmiiw":"correct me if i'm wrong",
"cmon":"come on",
"cmp":"creative multiplayer",
"cms":"content management system",
"cnp":"continued next post",
"cnrhkyitf":"chuck norris roundhouse kick you in the face",
"coa":"course of action",
"cob":"close of business",
"coc":"code of conduct",
"cod":"call of duty",
"col":"crying out loud",
"combo":"combination",
"comp":"computer",
"convo":"conversation",
"coo":"cool",
"cos":"child over shoulder",
"cp":"club penguin",
"cpe":"coolest person ever",
"cqc":"close quarters combat",
"cracka":"white person",
"cray":"crazy",
"crb":"come right back",
"crbt":"crying real big tears",
"crd":"caucasian rhythm disorder",
"cre8":"create",
"crew":"group of friends",
"crib":"house",
"crimbo":"christmas",
"crit":"critical strike",
"crn":"chuckling right now",
"crs":"can't remember stuff",
"crt":"cathode ray tube",
"crtla":"can't remember the three letter acronym",
"crz":"crazy",
"cs":"creep score",
"cs":"chatslang.com",
"cs":"caesarean section",
"csb":"cool story, bro",
"csg":"chuckle snicker grin",
"csl":"can't stop laughing",
"css":"cascading style sheet",
"ctc":"call the cell",
"ctf":"capture the flag",
"ctfu":"cracking the fuck up",
"cthu":"cracking the heck up",
"ctm":"complete the monument",
"ctm":"chuckle to myself",
"ctn":"can't talk now",
"cto":"check this out",
"ctr":"center",
"ctrn":"can't talk right now",
"cts":"change the subject",
"cu":"see you",
"cu2":"see you too",
"cu2mr":"see you tomorrow",
"cu46":"see you for sex",
"cu@":"see you around",
"cub":"call you back",
"cud":"could",
"cul":"call you later",
"cul":"see you later",
"cul":"catch you later",
"cul8r":"call you later",
"cul8r":"see you later",
"cul8rm8":"see you later m8",
"cula":"see you later alligator",
"cuol":"see you online",
"cus":"see you soon",
"cushty":"cool",
"cuz":"because",
"cwot":"complete waste of time",
"cwyl":"chat with you later",
"cx":"correction",
"cya":"see ya",
"cyal8r":"see you later",
"cyb":"call you back",
"cydi":"can ya dig it",
"cye":"check your e-mail",
"cyf":"check your facebook",
"cyfb":"check your facebook",
"cyl":"catch ya later",
"cym":"check your myspace",
"cyo":"see you online",
"cyoa":"cover your own ass",
"cyr":"call your",
"cyt":"see you tomorrow",
"cyww2by":"see ya, wouldn't want to be ya",
"cz":"because",
"d/c":"disconnected",
"d/c":"don't care",
"d/l":"download",
"d/s":"dominant/submissive",
"d3":"diablo 3",
"d8":"date",
"da":"dumb ass",
"da":"the",
"dah":"dumb ass hole",
"dal":"dalaran",
"daq":"dumb asked question",
"dar":"daily afternoon randomness",
"dashie":"rainbow dash",
"dat":"that",
"dbag":"douchebag",
"dbd":"don't be dumb",
"dbeyr":"don't believe everything you read",
"dbg":"don't be gay",
"dbm":"deadly boss mods",
"dbmn":"don't bug me now",
"dbs":"dad behind shoulder",
"dbts":"don't believe that stuff",
"dbts":"don't believe their suck",
"dc":"disconnect",
"dc":"daycare",
"dced":"disconnected",
"dd":"dear daughter",
"ddg":"drop dead gorgeous",
"ddsos":"different day, same old stuff",
"de":"disenchant",
"deagle":"desert eagle",
"debuff":"weakening effect",
"dece":"decent",
"ded":"dead",
"deeps":"damage per second",
"deets":"details",
"def":"definitely",
"def":"defense",
"degt":"don't even go there",
"delish":"delicious",
"dept":"department",
"der":"duh",
"derp":"expression of stupidity",
"detweet":"to delete a tweet",
"dewd":"dude",
"df":"dear fiance",
"dfg":"deathfire grasp",
"dfl":"dead freaking last",
"dftba":"don't forget to be awesome",
"dga":"digital guardian angel",
"dga":"don't go anywhere",
"dgara":"don't give a rat's ass",
"dh":"dear hubby",
"dh":"dear husband",
"dhtc":"don't hit the cell",
"dhyb":"don't hold your breath",
"diaf":"die in a fire",
"dibs":"rights to something",
"dig":"like",
"digits":"phone number",
"diik":"darned if i know",
"diku":"do i know you?",
"diky":"do i know you?",
"dil":"daughter-in-law",
"dilligaf":"do i look like i give a flip?",
"dilligaff":"does it look like i give a flying flip?",
"ding":"level up",
"dink":"double income no kids",
"dip":"idiot",
"dip":"leave",
"dis":"disrespect",
"dis":"this",
"disc":"discipline",
"diss":"disrespect",
"distol":"did i say that out loud?",
"ditg":"down in the gutter",
"ditto":"same",
"diva":"rude woman",
"diy":"do it yourself",
"dk":"don't know",
"dkdc":"don't know, don't care",
"dkp":"dragon kill points",
"dl":"down low",
"dl":"download",
"dl":"doing laundry",
"dlc":"downloadable content",
"dlm":"don't leave me",
"dlo":"down low",
"dltbbb":"don't let the bed bugs bite",
"dltcu":"don't let them catch you",
"dltm":"don't lie to me",
"dm":"direct message",
"dm":"death match",
"dm":"do me",
"dmb":"dave matthews band",
"dmg":"damage",
"dmi":"don't mention it",
"dmnds":"doesn't make no dang sense",
"dmy":"don't mess yourself",
"dnbl8":"do not be late",
"dnd":"do not disturb",
"dnftt":"do not feed the trolls",
"dno":"don't know",
"dnt":"don't",
"doa":"dead on arrival",
"doc":"drug of choice",
"doge":"dog",
"dogface":"ugly",
"dom":"dirty old man",
"dom":"dominate",
"dome":"head",
"domed":"headshotted",
"don":"double or nothing",
"doo":"dude",
"doo":"excrement from a human or an animal",
"doo-doo":"child term for human or animal excrement",
"dood":"dude",
"dos":"dad over shoulder",
"dot":"damage over time",
"dota":"defense of the ancients",
"douche":"douchebag",
"douchebag":"arrogant jerk",
"doucheling":"partial douchebag",
"dough":"money",
"dougie":"dance move",
"dp":"dear partner",
"dps":"damage per second",
"dq":"disqualify",
"dqmot":"don't quote me on this",
"dqotd":"dumb question of the day",
"dqydj":"don't quit your day job",
"drc":"don't really care",
"drk":"don't really know",
"drm":"digital rights management",
"ds":"dear son",
"dsi":"don't sweat it",
"dsr":"detailed seller rating",
"dstr8":"dang straight",
"dt":"dang typos",
"dt":"dark templar",
"dt":"dream theater",
"dtf":"down to fuck",
"dtr":"define the relationship",
"dtrt":"do the right thing",
"du":"don't understand",
"du":"darn you",
"duckroll":"to mislead someone",
"duh":"overly obvious",
"duk":"didn't you know?",
"dulm":"do you love me",
"dunking":"owning enemy player",
"dunno":"i don't know",
"dur":"do you remember",
"dur":"stupidly obvious",
"duut":"do you understand that?",
"dw":"don't worry",
"dw":"dear wife",
"dwb":"don't write back",
"dwbh":"don't worry, be happy",
"dweet":"drunk tweet",
"dwhtgtta":"do we have to go through this again",
"dwisnwid":"do what i say, not what i do",
"dwl":"dying with laughter",
"dwt":"driving while texting",
"dwts":"dancing with the stars",
"dx":"driving",
"dyd":"don't you dare",
"dyfi":"did you find it",
"dyhab":"do you have a boyfriend?",
"dyhag":"do you have a girlfriend?",
"dyjhiw":"don't you just hate it when",
"dyk":"did you know",
"dylm":"do you like me",
"dylm":"do you love me",
"dym":"did you mean",
"dytth":"did you talk to him?",
"dytth":"did you talk to her?",
"e-ok":"electronically ok",
"e1":"everyone",
"e2eg":"ear to ear grin",
"ea":"electronic arts",
"ea":"each",
"eak":"eating at keyboard",
"eavestweeting":"eavesdropping on twitter conversations",
"effin":"fucking",
"eg":"evil grin",
"eg":"for example",
"ei":"eat it",
"eie":"enough is enough",
"elo":"electric light orchestra",
"elo":"elo rating system",
"em":"e-mail",
"ema":"e-mail address",
"emc2":"genius",
"emi":"excuse my ignorance",
"eml":"email me later",
"emo":"emotional",
"emsg":"e-mail message",
"endie":"enderman",
"engrish":"bad asian to english translation",
"enuf":"enough",
"eod":"end of discussion",
"eof":"end of file",
"eol":"end of lecture",
"eol":"end of line",
"eol":"end of life",
"eom":"end of message",
"eor":"end of rant",
"eot":"end of thread",
"epm":"effective actions per minute",
"epo":"erythropoietin",
"ermahgerd":"oh my gosh",
"errz":"errors",
"esad":"eat suck and die",
"esl":"electronic sports league",
"esports":"electronic sports",
"essench":"essential",
"eta":"estimated time of arrival",
"eta":"edited to add",
"etd":"estimated time of departure",
"euc":"excellent used condition",
"eva":"ever",
"every1":"everyone",
"evs":"whatever",
"exp":"experience",
"eyc":"excited yet calm",
"ez":"easy",
"ezpz":"easy peasy",
"ezy":"easy",
"f":"female",
"f/f":"face to face",
"f11":"finger eleven",
"f2f":"face to face",
"f2p":"free to play",
"f2t":"free to talk",
"f9":"fine",
"fab":"fabulous",
"facepalm":"to place the palm of your hand on your face",
"facestalking":"looking through someone's pictures on facebook",
"faf":"funny as fluff",
"fah":"funny as heck",
"fail":"failure",
"fanboy":"big fan",
"fantabulous":"better than fantastic or fabulous",
"faq":"frequently asked questions",
"fav":"favorite",
"fave":"favorite",
"favs":"favorites",
"fawc":"for anyone who cares",
"fb":"facebook",
"fb":"feedback",
"fbc":"facebook chat",
"fbf":"facebook friend",
"fbm":"fine by me",
"fbo":"facebook official",
"fbow":"for better or worse",
"fbtw":"fine, be that way",
"fc":"fingers crossed",
"fcfs":"first-come, first-served",
"fcol":"for crying out loud",
"fe":"finger eleven",
"feds":"federal agents",
"fella":"fellow person",
"ff":"flying fadoodle",
"ff":"fast forward",
"ff":"faerie fire",
"ff":"focus fire",
"ff":"final fantasy",
"ff":"friends forever",
"ff":"freeze frame",
"ff":"follow friday",
"ff5":"family force 5",
"ffa":"free for all",
"ffdp":"five finger death punch",
"ffe":"forge fast expand",
"fff":"fight for first",
"ffs":"for fuck's sake",
"ffwe":"finds fault with everything",
"fgs":"for goodness sake",
"fgsqtc":"for gosh's sake quit the crap",
"fh":"fucking heck",
"fh":"future husband",
"fho":"friends hanging out",
"ficcl":"frankly, i couldn't care less",
"fifo":"first in, first out",
"fil":"father-in-law",
"finna":"fixing to",
"fitb":"fill in the blanks",
"fitty":"fifty",
"fla":"four letter acronym",
"flex":"to show off",
"fmi":"for more information",
"fmj":"full metal jacket",
"fml":"fuck my life",
"fn":"fine",
"fnb":"football and beer",
"fng":"flippin' new guy",
"fo":"freaking out",
"fo":"far out",
"fo":"sho for sure",
"foaf":"friend of a friend",
"fob":"fresh off the boat",
"foc":"free of charge",
"focl":"falling off the chair laughing",
"fofl":"falling on the floor laughing",
"foflmao":"falling on the floor laughing my ass off",
"foh":"fuck outta here",
"fomcl":"fell out of my chair laughing",
"fomo":"fear of missing out",
"fomoh":"fear of missing out on hockey",
"foomcl":"falling out of my chair laughing",
"fos":"freedom of speech",
"fos":"feat of strength",
"fos":"figure of speech",
"fotcl":"falling off the chair laughing",
"fotd":"face of the day",
"fotfl":"falling on the floor laughing",
"fotflmao":"falling on the floor laughing my ass off",
"fotflol":"falling on the floor, laughing out loud",
"fouo":"for official use only",
"fp":"flight point",
"fps":"frames per second",
"fps":"first-person shooter",
"fr":"for real",
"frag":"player kill",
"frealz":"for real",
"freebie":"free item",
"fri":"endless friend",
"frnd":"friend",
"fro":"afro",
"frontin":"to pretend you are something you are not",
"fs":"full screen",
"fs":"for sale",
"fsbo":"for sale by owner",
"fse":"funniest suck ever",
"fsr":"for some reason",
"ftbomh":"from the bottom of my heart",
"ftc":"failure to communicate",
"ftel":"for the epic loss",
"ftew":"for the epic win",
"ftf":"face to face",
"ftfoi":"for the fun of it",
"ftfy":"fixed that for you",
"ftg":"for the group",
"ftk":"for the kill",
"ftl":"for the loss",
"ftmfw":"for the mother fucking win",
"ftmp":"for the most part",
"ftp":"file transfer protocol",
"ftr":"for the record",
"ftr":"after",
"fttb":"for the time being",
"fttt":"from time to time",
"ftw":"for the win",
"fu":"fully understood",
"fu":"fuck you",
"fubar":"fouled up beyond all recognition",
"fuct":"failed under continuous testing",
"fud":"fear, uncertainty, and doubt",
"fugly":"fucking ugly",
"fum":"fouled up mess",
"fusit":"fouled up situation",
"fut":"follow up to",
"fvf":"final value fee",
"fw":"freeware",
"fw":"future wife",
"fwb":"friends with benefits",
"fwbl":"friends with better lives",
"fwd":"forward",
"fwiw":"for what it's worth",
"fwm":"fine with me",
"fya":"for your amusement",
"fye":"for your entertainment",
"fyeo":"for your eyes only",
"fyf":"from your friend",
"fyi":"for your information",
"fyki":"for your kind information",
"fyl":"fuck your life",
"fym":"for your misinformation",
"g/f":"girlfriend",
"g1":"good one",
"g2b":"going to bed",
"g2cu":"good to see you",
"g2g":"good to go",
"g2g":"gotta go",
"g2ggs2d":"got to go get something to drink",
"g2giam":"got to go in a minute",
"g2gp":"got to go pee",
"g2k":"good to know",
"g2p":"gone to pee",
"g2pb":"got to pee badly",
"g2r":"got to run",
"g2tu":"got to tell you",
"g4i":"go for it",
"g4n":"good for nothing",
"g4u":"good for you",
"g6":"gulfstream g650",
"g8r":"gator",
"g9":"genius",
"g9":"goodnight",
"ga":"go ahead",
"ga":"good afternoon",
"gad":"get a dictionary",
"gag":"got any gossip?",
"gal":"get a life",
"galma":"go away, leave me alone",
"gamer":"video game player",
"gank":"steal",
"gas":"gear acquisition syndrome",
"gas":"greetings and salutations",
"gat":"gun",
"gawd":"god",
"gawma":"go ahead, whet my appetite",
"gb":"guild bank",
"gb":"gigabyte",
"gb":"goodbye",
"gb2w":"get back to work",
"gba":"gameboy advance",
"gbfn":"goodbye for now",
"gbh":"great big hug",
"gbh&k":"great big hug and kiss",
"gbhk":"great big hug and kiss",
"gbr":"garbled beyond recovery",
"gbttd":"got better things to do",
"gbtw":"get back to work",
"gby":"god bless you",
"gc":"good crib",
"gc":"groovy cat",
"gd":"green day",
"gd":"good day",
"gd&h":"grinning, ducking, and hiding",
"gd&r":"grinning, ducking, and running",
"gd&rvf":"grinning, ducking, and running very fast",
"gdr":"grinning, ducking, running",
"ge":"good evening",
"gerd":"oh my gosh!",
"gf":"gluten-free",
"gf":"girlfriend",
"gfete":"grinning from ear to ear",
"gfg":"good friggin' game",
"gfn":"gone for now",
"gftd":"gone for the day",
"gfu":"good for you",
"gfy":"go fuck yourself",
"gfy":"good for you",
"gg":"good grief",
"gg":"good game",
"gga":"good game all",
"ggg":"gotta get a grip",
"ggg":"giggle",
"gggb":"good girl gone bad",
"ggl":"good game loser",
"gglords":"broodlords",
"ggogg":"great gobs of goose grease",
"ggoh":"gotta get out of here",
"ggp":"gotta go pee",
"ggs":"good games",
"gh":"good half",
"ghetto":"blaster large, portable radio",
"ghosting":"observing an enemy player",
"gi":"good idea",
"gi":"glycemic index",
"gibs":"giblets",
"gic":"god's in control",
"gicbts":"gosh, i can't believe that stuff",
"gicnby":"gosh, i cannot believe you",
"gif":"graphics interchange format",
"gig":"god is good",
"gigo":"garbage in, garbage out",
"git":"get over it",
"giwisi":"gee, i wish i said it",
"giwist":"gee, i wish i'd said that",
"gj":"good job",
"gjp":"good job partner",
"gk":"go know",
"gl":"get lost",
"gl":"good luck",
"gl&gh":"good luck and good hunting",
"gl2u":"good luck to you",
"gle":"good luck everyone",
"glhf":"good luck have fun",
"glhfttyl":"good luck, have fun, talk to you later",
"glwt":"good luck with that",
"gm":"good morning",
"gm":"game master",
"gm":"good move",
"gm":"grandmaster",
"gm":"good match",
"gma":"grandma",
"gmab":"give me a break",
"gmafb":"give me a friggin' break",
"gmta":"great minds think alike",
"gmv":"got my vote",
"gn":"goodnight",
"gn":"get naked",
"gne1":"good night everyone",
"gnight":"good night",
"gnite":"goodnight",
"gno":"girls night out",
"gnoc":"get naked on camera",
"gnr":"guns n' roses",
"gnst":"good night, sleep tight",
"gogo":"go now",
"gok":"god only knows",
"gol":"groaning out loud",
"gol":"giggle out loud",
"gomb":"get off my back",
"goml":"get on my level",
"gonna":"going to",
"goon":"idiot",
"gorge":"gorgeous",
"gosu":"highly skilled",
"gotcha":"i get you",
"goty":"game of the year",
"gow":"gears of war",
"gow2":"gears of war 2",
"gowi":"get on with it",
"gowm":"go out with me",
"gp":"go private",
"gpa":"grandpa",
"gpa":"grade point average",
"gpoy":"gratuitous picture of yourself",
"gpoyw":"gratuitous picture of yourself wednesday",
"gps":"god's positioning system",
"gps":"global positioning system",
"gpw":"global password",
"gr":"gotta run",
"gr&d":"grinning, running, and ducking",
"gr8":"great",
"grats":"congratulations",
"gratz":"congratulations",
"griefer":"irritating player",
"griefing":"to irritate other players",
"grl":"girl",
"grool":"great and cool",
"grr":"anger",
"grrlz":"girls",
"gs":"good shot",
"gs":"gear score",
"gshiwmp":"giggling so hard i wet my pants",
"gsl":"global starcraft league",
"gsoh":"great sense of humor",
"gstl":"global starcraft team league",
"gsw":"got some weed",
"gt2t":"got time to talk",
"gta":"grand theft auto",
"gtf":"gone too far",
"gtfo":"get the fuck out",
"gtfooh":"get the fuck out of here",
"gtg":"got to go",
"gtg":"good to go",
"gtk":"good to know",
"gtl":"gym, tan, laundry",
"gtm":"giggle to myself",
"gtpb":"got to pee badly",
"gtr":"got to run",
"gtrdun":"get 'er done",
"gtsy":"glad to see you",
"gu":"gently used",
"gud":"good",
"gufn":"grounded until further notice",
"gui":"graphical user interface",
"gv":"give",
"gvn":"given",
"gw":"good work",
"gyfo":"get your freak on",
"gysr":"gosh, you're so random",
"gz":"congratulations",
"h&k":"hugs and kisses",
"h/o":"hold on",
"h/p":"hold please",
"h/t":"hat tip",
"h/u":"hook up",
"h/w":"husband and wife",
"h/w":"homework",
"h2cus":"hope to see you soon",
"h4u":"hot for you",
"h4x0r":"hacker",
"h4x0rz":"hackers",
"h8":"hate",
"h8r":"hater",
"h8t":"hate",
"h9":"husband in room",
"ha":"hello again",
"habd":"have a blessed day",
"hag1":"have a good one",
"haga":"have a good afternoon",
"hagd":"have a good day",
"hagn":"have a good night",
"hago":"have a good one",
"hags":"have a great summer",
"hagw":"have a good week",
"haha":"laughing",
"hai":"hi",
"hak":"hugs and kisses",
"han":"how about now?",
"hangry":"angry because you're hungry",
"hater":"someone who's angry or jealous of someone",
"haterade":"the drink of someone who disapproves of another's actions/lifestyle",
"hav":"have",
"hax":"hacks",
"haxor":"hacker",
"hay":"how are you",
"hb":"hug back",
"hb":"hurry back",
"hb2u":"happy birthday to you",
"hbbd":"happy belated birthday",
"hbd":"happy birthday",
"hbo":"home box office",
"hbu":"how 'bout you",
"hby":"how about you?",
"hc":"how cool",
"hcit":"how cool is that",
"hdd":"hard disk drive",
"hdtv":"high definition tv",
"hdylmn":"how do you like me now",
"hehe":"laughing",
"hf":"have fun",
"hfc":"holy freaking crap",
"hft":"high frequency trader",
"hgh":"human growth hormone",
"hh":"ha-ha",
"hh":"holding hands",
"hh1/2ko":"ha-ha, half-kidding only",
"hhis":"hanging head in shame",
"hhjk":"ha-ha, just kidding",
"hhoj":"ha-ha only joking",
"hhoj/k":"ha-ha, only just kidding",
"hhok":"ha-ha only kidding",
"hhos":"ha-ha, only serious",
"hhsf":"ha-ha, so funny",
"hhvf":"ha-ha, very funny",
"hi5":"high five",
"hig":"how's it going?",
"hih":"hope it helps",
"himym":"how i met your mother",
"hipster":"alternative subculture",
"hiwth":"hate it when that happens",
"hk":"hugs and kisses",
"hk":"hello kitty",
"hl":"half-life",
"hlbd":"happy late birthday",
"hlm":"he loves me",
"hlp":"help",
"hm":"hard mode",
"hm":"home",
"hml":"hate my life",
"hmp":"help me, please",
"hmp":"half marathon pace",
"hmp":"humph",
"hmp":"hardcore multiplayer",
"hmph":"statement of disdain",
"hms":"hanging myself",
"hmsl":"holding my sides laughing",
"hmt":"here's my try",
"hmu":"hit me up",
"hmwk":"homework",
"hny":"happy new year",
"ho":"hold on",
"hoas":"hold on a second",
"hoas":"heck of a shot",
"hoc":"house of cards",
"hof":"hall of fame",
"hoic":"hold on, i'm coming",
"holla":"holler",
"hom":"hit or miss",
"hon":"heroes of newerth",
"hon":"honey",
"honkey":"white person",
"honkie":"white person",
"honky":"white person",
"hood":"neighborhood",
"hoops":"basketball",
"horribad":"horribly bad",
"horu":"how old are you",
"hos":"husband over shoulder",
"hottie":"attractive person",
"hp":"harry potter",
"hp":"horsepower",
"hp":"handphone",
"hp":"hit points",
"hp5":"health per five seconds",
"hpdc":"happy people don't complain",
"hps":"heals per second",
"hpt":"home pregnancy test",
"hr":"home run",
"hr":"human resources",
"hr":"homeroom",
"hru":"how are you",
"hry":"hurry",
"hs":"head shot",
"hs":"high school",
"hsik":"how should i know",
"hsm":"high school musical",
"hsmp":"homeschool me please",
"htc":"hit the cell",
"htf":"hard to find",
"hth":"hope this helps",
"html":"hyper-text markup language",
"htn":"high time now",
"htsus":"hope to see you soon",
"http":"hypertext transfer protocol",
"https":"hypertext transfer protocol secure",
"hu":"hang up",
"hu":"hold up",
"hu":"hook up",
"hubby":"husband",
"hud":"heads up display",
"hud":"how you doing?",
"hun":"honey",
"huzzah":"hooray",
"hw":"homework",
"hw":"hardware",
"hwga":"here we go again",
"hwik":"how would i know",
"hwk":"homework",
"hwp":"height weight proportionate",
"hwu":"hey, what's up?",
"hxc":"hardcore",
"hy":"heck yeah",
"hye":"have you ever",
"hyfr":"heck ya, freakin' right",
"hyh":"hold your horses",
"hyl":"help you later",
"h^":"hook up",
"i8":"i ate",
"i8u":"i hate you",
"ia":"i agree",
"iab":"in a bit",
"iac":"in any case",
"iad":"it all depends",
"iae":"in any event",
"iag":"it's all good",
"iagsmsol":"i am getting some money sooner or later",
"iagw":"in a good way",
"iail":"i am in love",
"iam":"in a minute",
"ianal":"i am not a lawyer",
"iap":"in-app purchase",
"iat":"alright",
"iat":"i am tired",
"iaw":"in accordance with",
"iawmp":"i almost wet my pants",
"iawtc":"i agree with the comment",
"iayf":"it's all your fault",
"ib":"i'm back",
"ib2d":"i beg to differ",
"ibtl":"in before the lock",
"ic":"i see",
"ic":"in character",
"icbw":"i could be wrong",
"icc":"icecrown citadel",
"iccl":"i couldn't care less",
"ichc":"i can has cheezburger?",
"ichi":"i can't help it",
"icl":"in christian love",
"ico":"in concern of",
"ico":"in care of",
"icocbw":"i could, of course, be wrong",
"icurnvs":"i see you are envious",
"icwym":"i see what you mean",
"icyc":"in case you're curious",
"icymi":"in case you missed it",
"id10t":"idiot",
"idc":"i don't care",
"idd":"indeed",
"idek":"i don't even know",
"idevice":"apple hardware",
"idfk":"i don't freaking know",
"idgaf":"i don't give a fuck",
"idgi":"i don't get it",
"idgra":"i don't give a rat's ass",
"idhi":"i don't have it",
"idi":"i doubt it",
"idk":"i don't know",
"idky":"i don't know why",
"idmb":"i'll do my best",
"idn":"i don't know",
"idndt":"i did not do that",
"idnk":"i do not know",
"idr":"i don't remember",
"ids":"i'm dead serious",
"idt":"i don't think",
"idts":"i don't think so",
"idtt":"i'll drink to that",
"idu":"i don't understand",
"ie":"that is",
"iem":"intel extreme masters",
"ifab":"i found a bug",
"ifly":"i freaking love you",
"ifocn":"in front of computer naked",
"ifsfy":"i feel sorry for you",
"ifvb":"i feel very bad",
"ig":"i guess",
"ig2p":"i got to pee",
"iggy":"ignored",
"ight":"alright",
"igi":"i get it",
"ign":"in-game name",
"igtp":"i get the point",
"ih8u":"i hate you",
"iha":"i hate acronyms",
"ihi":"i have it",
"ihm":"i hate mondays",
"ihu":"i hate you",
"ihy":"i hate you",
"ii":"i'm impressed",
"iiok":"if i only knew",
"iir":"if i remember",
"iirc":"if i remember correctly",
"iit":"i'm impressed too",
"iiuc":"if i understand correctly",
"iiwy":"if i were you",
"ijc2silu":"i just called to say i love you",
"ijdgaf":"i just don't give a fuck",
"ijwtk":"i just want to know",
"ijwts":"i just want to say",
"ik":"i know",
"ikhyf":"i know how you feel",
"ikr":"i know, right?",
"ikwum":"i know what you mean",
"ikwym":"i know what you mean",
"ikyd":"i know you did",
"ilamy":"i love and miss you",
"ill":"cool",
"ilmm":"i love my man",
"ilu":"i like you",
"ilu":"i love you",
"ilu2":"i love you too",
"ilub":"i love you baby",
"ilugtd":"i love you guys to death",
"ilum":"i love you man",
"iluvu":"i love you",
"ily":"i love you",
"ily2":"i love you too",
"ilyfae":"i love you forever and ever",
"ilyfe":"i love you for eternity",
"ilyk":"i'll let you know",
"ilyl":"i love you lots",
"ilylc":"i love you like crazy",
"ilymtywek":"i love you more than you would ever know",
"ilysm":"i love you so much",
"ilywamh":"i love you with all my heart",
"im":"instant messenger",
"im":"instant message",
"ima":"i'm going to",
"ima":"i'm",
"ima":"i might add",
"imao":"in my arrogant opinion",
"imba":"imbalanced",
"imbo":"in my biased opinion",
"imco":"in my considered opinion",
"imd":"in my dreams",
"ime":"in my experience",
"imharo":"in my humble and respectful opinion",
"imhbmao":"in my humble but most accurate opinion",
"imho":"in my humble opinion",
"imho":"in my honest opinion",
"imio":"in my infallible opinion",
"imma":"i'm gonna",
"imnsho":"in my not so humble opinion",
"imnsvho":"in my not so very humble opinion",
"imo":"in my opinion",
"imobo":"in my own biased opinion",
"imot":"i'm on that",
"impo":"in my personal opinion",
"impov":"in my point of view",
"ims":"if memory serves",
"ims":"i am sorry",
"imso":"in my sovereign opinion",
"imtg":"in meeting",
"imu":"i miss you",
"imvho":"in my very humble opinion",
"imvu":"instant messaging virtual universe",
"imy":"i miss you",
"imya":"i miss you already",
"inb4":"in before",
"inbd":"it's no big deal",
"inc":"incoming",
"indie":"independent",
"indy":"independent",
"indy":"indianapolis",
"info":"information",
"init":"initialize",
"inpo":"in no particular order",
"inr":"i know right",
"inrs":"it's not rocket science",
"instalock":"instantly choose character",
"int":"intellect",
"intel":"intelligence",
"intexticated":"texting while driving",
"inu":"i need you",
"inv":"invite",
"iob":"insulin on board",
"ioh":"i'm out of here",
"ioit":"i'm on irish time",
"iokiyad":"it's ok if you're a democrat",
"iokiyar":"it's ok if you're a republican",
"ion":"i don't",
"iono":"i don't know",
"iou":"i owe you",
"iow":"in other words",
"ipn":"i'm posting naked",
"ipo":"initial public offering",
"ipq":"internet printable coupon",
"ir":"in room",
"ir8":"irate",
"irdk":"i really don't know",
"irl":"in real life",
"irstbo":"it really sucks the big one",
"irt":"in regards to",
"isf":"insulin sensitivity factor",
"ish":"i'm so hungry",
"iso":"in search of",
"iso":"is seeking other",
"isp":"internet service provider",
"istm":"it seems to me",
"istr":"i seem to recall",
"iswym":"i see what you mean",
"itbootp":"in the bathroom, out of toilet paper",
"itfa":"in the final analysis",
"itigbs":"i think i'm going to be sick",
"itily":"i think i like you",
"itily":"i think i love you",
"itmt":"in the meantime",
"itr":"income tax return",
"itr":"internet talk radio",
"itr":"in the room",
"itrw":"in the real world",
"itsfwi":"if the shoe fits, wear it",
"ittwacw":"i thought this was a christian website",
"ityf":"i think you'll find",
"itym":"i think you mean",
"itys":"i told you so",
"iv":"interview",
"ivl":"in virtual life",
"iw2bwu":"i want to be with you",
"iwalu":"i will always love you",
"iwaly":"i will always love you",
"iwbb":"i will be back",
"iwbni":"it would be nice if",
"iwty":"i would tickle you",
"iwu":"i want you",
"iykwim":"if you know what i mean",
"iyo":"in your opinion",
"iyq":"i like you",
"iyss":"if you say so",
"iyswim":"if you see what i mean",
"iz":"is",
"j":"joking",
"j/k":"just kidding",
"j/p":"just playing",
"j/w":"just wondering",
"j2lyk":"just to let you know",
"j4f":"just for fun",
"j4g":"just for grins",
"jab":"injection",
"jaf":"just a friend",
"jaffas":"cookies",
"jam":"just a minute",
"janky":"of poor or inferior quality",
"jas":"just a second",
"jase":"just another system error",
"jb/c":"just because",
"jbc":"just because",
"jc":"just chilling",
"jc":"just checking",
"jc":"just curious",
"jc":"jewelcrafter",
"jci":"just checking in",
"jellz":"jealous",
"jet":"leave quickly",
"jff":"just for fun",
"jfgi":"just flippin' google it",
"jfi":"just for information",
"jfk":"just freakin' kidding",
"jic":"just in case",
"jit":"just in time",
"jj":"just joking",
"jja":"just joking around",
"jjwy":"just joking with you",
"jk":"just kidding",
"jlmk":"just let me know",
"jlo":"jennifer lopez",
"jluk":"just letting you know",
"jmho":"just my humble opinion",
"jmo":"just my opinion",
"jock":"athlete",
"jockin":"copy",
"jockin":"my style copycatting",
"john":"toilet",
"jooc":"just out of curiosity",
"jorts":"jean shorts",
"joshing":"joking",
"jp":"jurassic park",
"jp":"just playing",
"js":"just saying",
"jsyk":"just so you know",
"jtlyk":"just to let you know",
"juiced":"excited",
"juil":"just you i love",
"jw":"just wondering",
"k":"ok",
"k":"kiss",
"k3u":"i love you",
"kappa":"sarcasm",
"kara":"karazhan",
"kas":"kicking and screaming",
"kb":"kiss back",
"kb":"kilobyte",
"kcco":"keep calm and chive on",
"kcco":"keep calm and carry on",
"kda":"kills deaths assists",
"kdr":"kill death ratio",
"kek":"wow orcish laugh",
"kek":"korean laugh",
"keke":"korean laugh",
"kewl":"cool",
"kewt":"cute",
"kfc":"kid's fattening clinic",
"kfc":"kentucky fried chicken",
"kfy":"kiss for you",
"kgo":"ok, go",
"khuf":"know how you feel",
"khyf":"know how you feel",
"kia":"killed in action",
"kik":"laughing out loud",
"kimye":"kim kardashian and kanye west",
"kinda":"kind of",
"kir":"keepin' it real",
"kit":"keep in touch",
"kiting":"moving while avoiding attack",
"kk":"ok",
"kk":"kiss kiss",
"kkr":"kill kill ratio",
"kkwt":"knock knock, who's there?",
"kl":"kool",
"km":"kiss me",
"kma":"kiss my ass",
"kmab":"kiss my ass bitch",
"kmb":"kiss my butt",
"kml":"killing myself laughing",
"kmmfa":"kiss my mother fucking ass",
"kmp":"keep me posted",
"kmsl":"killing myself laughing",
"kmso":"knocked my socks off",
"kmuf":"kiss me you fool",
"knp":"ok, no problem",
"kol":"kiss on lips",
"kos":"kill on site",
"kos":"kid over shoulder",
"kosher":"acceptable",
"kotc":"kiss on the cheek",
"kotl":"kiss on the lips",
"kotor":"knights of the old republic",
"kptondl":"keep it on the down low",
"ks":"kill steal",
"ks":"kingslayer",
"ksc":"kinda sorta chuckle",
"kthx":"ok, thanks",
"kthxbai":"ok, thanks, bye",
"kthxbi":"ok thanks, bye",
"kutgw":"keep up the good work",
"kw":"know",
"kwim":"know what i mean",
"kwis":"know what i'm saying",
"kwl":"cool",
"kyfm":"kiss yourself for me",
"kysoti":"keep your stick on the ice",
"l":"laughing",
"l/f/e":"lovers forever",
"l2m":"listening to music",
"l2p":"learn to play",
"l33t":"leet",
"l4d":"left for dead",
"l4d2":"left for dead 2",
"l8":"late",
"l8er":"later",
"l8r":"later",
"l8rg8r":"later gator",
"la":"laughing a lot",
"laf":"laugh",
"laffing":"laughing",
"lafs":"love at first sight",
"lal":"laughing a lot",
"lal":"laugh a little",
"lam":"leave a message",
"lamer":"lame person",
"lan":"local area network",
"lane":"moba map path",
"laning":"staying in a lane",
"larp":"live action role-playing",
"larper":"live action role-player",
"larping":"live action role-playing",
"lawl":"lol",
"lawls":"laugh out loud",
"lawlz":"laugh out loud",
"lbf":"later, best friend",
"lbl":"light bladder leakage",
"lbr":"let's be real",
"lbvs":"laughing but very serious",
"lc":"let's celebrate",
"lcd":"liquid crystal display",
"ld":"later dude",
"ldr":"long distance relationship",
"lebroning":"flopping",
"led":"light-emitting diode",
"lefties":"liberals",
"legit":"legitimate",
"lemeno":"let me know",
"lep":"love emo people",
"lewt":"loot",
"lf":"looking for",
"lf1m":"looking for one more",
"lfd":"left for day",
"lfg":"looking for group",
"lfk":"let's french kiss",
"lfm":"looking for more",
"lftd":"left for the day",
"lftd":"laugh for the day",
"lfw":"looking for work",
"lgbt":"lesbian, gay, bisexual, and transgender",
"lgbtq":"lesbian, gay, bisexual, transgender, and queer",
"lhm":"lord help me",
"lho":"laughing head off",
"lhu":"lord help us",
"lhua":"lord help us all",
"li":"linkedin",
"lib":"liberal",
"lifo":"last in, first out",
"lig":"life is good",
"lil":"little",
"ling":"zergling",
"liq":"laughing inside quietly",
"lis":"laughing in silence",
"ljk":"lol just kidding",
"lk":"like",
"ll":"later loser",
"ll&p":"live long and prosper",
"llacp":"laughing like a crazy person",
"llc":"laughing like crazy",
"llello":"cocaine",
"llh":"laughing like heck",
"llol":"literally laughing out loud",
"llpof":"liar liar pants on fire",
"lls":"laughing like suck",
"llta":"lots and lots of thunderous applause",
"lm":"letters mailed",
"lma":"leave me alone",
"lmao":"laughing my ass off",
"lmaorof":"laughing my ass off rolling on the floor",
"lmaorotf":"laughing my ass off and rolling on the floor",
"lmaotc":"laughing my ass off the chair",
"lmbo":"laughing my butt off",
"lmfao":"laughing my fat ass off",
"lmfaopimp":"laughing my freaking ass off peeing in my pants",
"lmfbo":"laughing my fat butt off",
"lmfho":"laughing my freakin' heart out",
"lmgtfy":"let me google that for you",
"lmho":"laughing my head off",
"lmho":"laughing my hiney off",
"lmirl":"let's meet in real life",
"lmk":"let me know",
"lml":"love my life",
"lml":"laughing mad loud",
"lmo":"leave me one",
"lmo":"let's make out",
"lms":"like my status",
"lms":"learning management system",
"lms":"let me see",
"lmso":"laughing my socks off",
"lmwao":"laughing my white ass off",
"lnk":"love and kisses",
"loc":"load of crap",
"loe":"level of effort",
"lofl":"laughing out freakin' loud",
"loi":"laughing on the inside",
"lol":"laughing out loud",
"lola":"love often, laugh a lot",
"lolaws":"laugh out loud and with style",
"lolhk":"lots of love, hugs, and kisses",
"lolol":"lots of laugh out louds",
"lolroflmao":"laughing out loud, rolling on floor, laughing my ass off",
"lolusa":"laughing out loud until sides ache",
"lolz":"laugh out louds",
"lom":"low on mana",
"loml":"love of my life",
"lomlily":"light of my life, i love you",
"loot":"treasure",
"loq":"laugh out quietly",
"los":"line of sight",
"lotflol":"lying on the floor laughing out loud",
"loti":"laughing on the inside",
"lotr":"lord of the rings",
"lotv":"legacy of the void",
"lqtm":"laughing quietly to myself",
"lrl":"laugh real loud",
"lru":"least recently used",
"lshifomd":"laughing so hard i fell off my dinosaur",
"lshmsfoaidmt":"laughing so hard my sombrero fell off and i dropped my taco",
"lshtmsfoaidmt":"laughing so hard that my sombrero fell off and i dropped my taco",
"lss":"long story short",
"lst":"long-sleeve t-shirt",
"ltd":"lovers till death",
"lthtt":"laughing too hard to type",
"ltm":"laughing to myself",
"ltmq":"laughing to myself quietly",
"ltns":"long time, no see",
"ltp":"let's talk privately",
"ltr":"later",
"ltr":"long term relationship",
"ltr":"letter",
"lts":"laughing to self",
"lu":"love you",
"lu4ever":"love you forever",
"lua":"love you a lot",
"lub":"love you, bye",
"lugls":"love you guys like sisters",
"lul":"love you lots",
"lulab":"love you like a brother",
"lulaf":"love you like a friend",
"lulas":"love you like a sister",
"lulz":"lol",
"lum":"love you man",
"lupp":"luckiest person on the planet",
"luv":"love",
"luzr":"loser",
"lv":"love",
"lv1":"leave one",
"lvl":"level",
"lwt":"laughing with tears",
"ly":"love ya",
"lya":"love you always",
"lyk":"let you know",
"lyl":"love you lots",
"lylab":"love you like a brother",
"lylas":"love you like a sister",
"lylc":"love you like crazy",
"lymi":"love you, mean it",
"lyn":"lying",
"lysm":"love you so much",
"lz":"led zeppelin",
"m":"male",
"m$":"microsoft",
"m.02":"my two cents",
"m/f":"male or female",
"m02":"my two cents",
"m8":"mate",
"mab":"maybe",
"maccas":"mcdonald's",
"mack":"flirt",
"macro":"economy management skill",
"mag":"magazine",
"main":"main character",
"manscaping":"strategic shaving of male body hair",
"mats":"materials",
"mb":"my bad",
"mb":"megabyte",
"mbf":"my best friend",
"mbp":"macbook pro",
"mbps":"megabits per second",
"mbs":"mom behind shoulder",
"mc":"mind control",
"mc":"minecraft",
"mcconaughssance":"matthew mcconaughey's renaissance",
"mcd":"mcdonald's",
"mcds":"mcdonald's",
"mcm":"man-crush monday",
"mcr":"my chemical romance",
"md@u":"mad at you",
"md@ufn":"mad at you for now",
"mdi":"multiple daily injections",
"mdiac":"my dad is a cop",
"mdps":"melee damage per second",
"me2":"me too",
"mech":"mechanical units",
"meds":"medications",
"mego":"my eyes glaze over",
"meh":"whatever",
"metagame":"outside game preparation and strategies",
"mf":"mother fucker",
"mfb":"mother fucking bitch",
"mgb":"may god bless",
"mgmt":"management",
"mhm":"mm-hmm",
"mhoty":"my hat's off to you",
"mi":"marching illini",
"mia":"missing in action",
"mib":"mint in box",
"mib":"men in black",
"mibg":"mental image be gone",
"micro":"unit micromanagement skill",
"mid":"middle lane",
"mid":"middle",
"mil":"mother-in-law",
"mimas":"may i make a suggestion",
"min":"minute",
"mins":"minutes",
"mips":"millions of instructions per second",
"mir":"mail-in rebate",
"mirl":"meet in real life",
"mishu":"miss you",
"mistweet":"tweet mistake",
"mk":"okay",
"mka":"make additions",
"mkay":"ok",
"mlb":"major league baseball",
"mlg":"major league gaming",
"mlia":"my life is average",
"mlp":"my little pony",
"mm":"merry meet",
"mm":"music monday",
"mm":"missing my",
"mm":"make me",
"mma":"meet me at",
"mma":"mixed martial arts",
"mmamp":"meet me at my place",
"mmb":"message me back",
"mmbbg":"massively multiplayer browser-based game",
"mmfu":"my mate fancies you",
"mmhrd":"many many happy returns of the day",
"mmk":"ok",
"mml":"made me laugh",
"mmm":"marine, marauder, medivac",
"mmo":"massively multiplayer online",
"mmob":"mind my own business",
"mmog":"massively multiplayer online game",
"mmorpg":"massively multiplayer online role-playing game",
"mmrd":"my mind is rolled down",
"mms":"multimedia messaging service",
"mng":"manage",
"mngr":"manager",
"mo":"more",
"mo":"modus operandi",
"moar":"more",
"mob":"monster",
"mob":"mobile",
"mob":"minecraft creature",
"moba":"multiplayer online battle arena",
"mod":"modification",
"mod":"moderator",
"mofo":"mother fucking",
"moh":"medal of honor",
"moh":"maid of honor",
"mojo":"attractive talent",
"moo":"my own opinion",
"mooc":"massive open online course",
"mooch":"freeload",
"moolah":"money",
"mooshroom":"minecraft mob",
"mop":"mists of pandaria",
"morf":"male or female",
"mos":"mom over shoulder",
"moss":"chill",
"motas":"members of the appropriate sex",
"motd":"message of the day",
"motos":"members of the opposite sex",
"motss":"members of the same sex",
"motu":"mark of the unicorn",
"motu":"masters of the universe",
"mp":"merry part",
"mp5":"mana per five seconds",
"mq":"manufacturer coupon",
"mr":"mentally retarded",
"mra":"men's rights activist",
"mrt":"modified retweet",
"mru":"most recently used",
"ms":"microsoft",
"ms":"miss",
"msb":"my sexy bitch",
"msft":"microsoft",
"msg":"message",
"msrp":"manufacturer's suggested retail price",
"mst":"must see today",
"mst3k":"mystery science theater 3000",
"mt":"modified tweet",
"mt":"mistype",
"mtf":"more to follow",
"mtfbwu":"may the force be with you",
"mtfbwy":"may the force be with you",
"mtg":"meeting",
"mth":"month",
"mu":"miss you",
"mu@":"meet you at",
"muah":"kiss",
"mubar":"messed up beyond all recognition",
"mud":"multi-user dimension",
"mula":"money",
"mule":"alternate character for storage",
"mum":"mom",
"mut":"mutilate",
"muta":"mutalisks",
"mvh":"with best regards",
"mvp":"most valuable player",
"mw":"most welcome",
"mwa":"kiss",
"mwah":"kiss",
"mwahugz":"kisses and hugs",
"myb":"myyearbook",
"myob":"mind your own business",
"mysp":"myspace",
"n/a":"not available",
"n/a":"not applicable",
"n/c":"not cool",
"n/c":"no comment",
"n/m":"nevermind",
"n/m/h":"nothing much here",
"n/r":"no reserve",
"n00b":"newbie",
"n1":"nice one",
"n1c":"no one cares",
"n2m":"not too much",
"n2mh":"not too much here",
"n2w":"not to worry",
"n64":"nintendo 64",
"n8kd":"naked",
"nac":"not a chance",
"nah":"no",
"nal":"nationality",
"narc":"tattle tale",
"nark":"informant",
"naw":"no",
"nax":"naxxaramas",
"naxx":"naxxaramas",
"nb":"please note",
"nb":"not bad",
"nba":"national basketball association",
"nbd":"no big deal",
"nbjf":"no brag, just fact",
"nbl":"not bloody likely",
"nbsp":"no bull suck please",
"nc":"no comment",
"nc":"nice call",
"nc":"not cool",
"ncz":"no capture zone",
"nd":"and",
"nds":"nintendo ds",
"ne":"any",
"ne1":"anyone",
"ne1er":"anyone here",
"ned":"no expiration date",
"neh":"no",
"nemore":"anymore",
"nerf":"weaken",
"nes":"nintendo entertainment system",
"netherrack":"nether block",
"nethng":"anything",
"netiquette":"net ettiquette",
"neva":"never",
"neway":"anyway",
"newaze":"anyways",
"newb":"newbie",
"nf":"not funny",
"nfc":"national football conference",
"nfi":"no further information",
"nfi":"no freaking idea",
"nfiah":"never fear, i am here",
"nfl":"not freakin' likely",
"nfl":"national football league",
"nfw":"no freakin' way",
"ng":"no good",
"ngl":"not gonna lie",
"nh":"nice hand",
"nhl":"national hockey league",
"nib":"new in box",
"nimby":"not in my backyard",
"nin":"nine inch nails",
"ninja":"loot stealer",
"nip":"new in package",
"nite":"night",
"nitm":"not in the mood",
"nj":"no joke",
"nj":"nice job",
"nk":"no kidding",
"nkotb":"new kids on the block",
"nkotbsb":"new kids on the block and backstreet boys",
"nkz":"no kill zone",
"nl":"national league",
"nl":"not likely",
"nl":"no limit",
"nlt":"no later than",
"nm":"nevermind",
"nm":"not much",
"nmh":"not much here",
"nmhjc":"not much here, just chilling",
"nmjc":"nothing much, just chillin'",
"nmjcy":"not much, just chilling, you?",
"nmp":"not my problem",
"nmtn":"nevermind that now",
"nmu":"not much, you?",
"nn2r":"no need to reply",
"nnito":"not necessarily in that order",
"nnto":"no need to open",
"nntr":"no need to reply",
"no1":"no one",
"nobmr":"none of my business, right",
"noirl":"no one is really laughing",
"nom":"no offense meant",
"nomb":"none of my business",
"noob":"newbie",
"nooblet":"young newbie",
"nooblord":"ultimate newbie",
"nos":"new old stock",
"notch":"minecraft creator",
"notd":"nail of the day",
"nottie":"unattractive person",
"nottomh":"not off the top of my head",
"noyb":"none of your business",
"np":"neopets",
"np":"nice play",
"np":"no problem",
"npc":"non-player character",
"nps":"no problem sweetie",
"nr":"no reserve",
"nrfb":"never removed from box",
"nrn":"no reply necessary",
"nrn":"not right now",
"ns":"nice shot",
"ns":"no suck",
"nsa":"no strings attached",
"nsfv":"not safe for vegetarians",
"nsfw":"not suitable for women",
"nsfw":"not safe for work",
"nsisr":"not sure if spelled right",
"nss":"no suck sherlock",
"nt":"nice try",
"nt":"no thanks",
"ntim":"not that it matters",
"ntl":"never too late",
"ntmy":"nice to meet you",
"ntn":"no thanks needed",
"nts":"note to self",
"nty":"no thank you",
"nub":"newbie",
"nuff":"enough",
"nufn":"nothing",
"nuigb":"not until i get back",
"nuke":"nuclear missile",
"num":"tasty",
"nvm":"nevermind",
"nvr":"never",
"nvrm":"nevermind",
"nw":"no way",
"nwo":"new world order",
"nwo":"new world order",
"nwot":"new without tags",
"nwt":"new with tags",
"nxt":"next",
"nyb":"not your business",
"o&o":"over and out",
"o4u":"only for you",
"oa":"over acting",
"oao":"over and out",
"oar":"on a roll",
"obo":"or best offer",
"obs":"obviously",
"obtw":"oh, by the way",
"obv":"obviously",
"obvi":"obviously",
"oc":"of course",
"ocd":"obsessive compulsive disorder",
"od":"overdose",
"oem":"original equipment manufacturer",
"ofc":"of course",
"ofl":"out for lunch",
"og":"original gangster",
"ogw":"oh gosh why",
"oh":"overheard",
"oh":"snap expression of surprise",
"ohemgee":"oh my gosh",
"oic":"oh, i see",
"oicn":"oh, i see now",
"oitnb":"orange is the new black",
"oiy":"hi",
"oj":"orange juice",
"ok":"one kiss",
"ol":"old lady",
"olpc":"one laptop per child",
"oltl":"one life to live",
"om":"old man",
"om":"oh man",
"omaha":"change of plans",
"omam":"of mice and men",
"omam":"of monsters and men",
"omc":"oh my carlisle",
"omd":"oh my darn!",
"omdb":"over my dead body",
"ome":"oh my edward",
"omfg":"oh my freaking gosh",
"omfgaz":"oh my freaking gosh and zounds",
"omfgyasb":"oh my freaking gosh, you're a sexy beast",
"omg":"oh my gosh",
"omgd":"oh my gosh, duh",
"omgf":"oh my godfather",
"omgn":"oh my gosh noob",
"omgroflmao":"oh my gosh, rolling on the floor laughing my ass off",
"omgwtfbbq":"oh my gosh, what the fuck, barbeque",
"omgys":"oh my gosh you suck",
"omh":"oh my heavens!",
"omj":"oh my jonas",
"oml":"oh my l...",
"omm":"on my mind",
"omohod":"one minute, one hour, one day",
"omw":"on my way",
"onco":"or nearest cash offer",
"oneshot":"one shot completion",
"onl":"online",
"onna":"oh no, not again",
"ono":"or nearest offer",
"onoz":"oh no",
"onyd":"oh no you didn't",
"oo":"on order",
"oo":"over and out",
"oo":"openoffice",
"ooak":"one of a kind",
"ooc":"out of character",
"ooh":"out of here",
"oom":"out of mana",
"oomf":"great strain",
"oomf":"one of my followers",
"ooo":"out of office",
"oop":"out of print",
"oop":"out of pocket",
"oot":"out of town",
"oot":"out of topic",
"ootb":"out of the box",
"ootd":"outfit of the day",
"ooyfm":"out of your freaking mind",
"op":"overpowered",
"op":"original poster",
"op":"operator",
"opa":"greek exclamation",
"opi":"overpaid idiot",
"opk":"ovulation predictor kit",
"opm":"other people's money",
"orly":"oh really",
"orp":"original retail price",
"oslt":"or something like that",
"ot":"other topic",
"ot":"off topic",
"ot":"overtime",
"ota":"over the air",
"otay":"okay",
"otb":"off the boat",
"otc":"over the counter",
"ote":"over the edge",
"otflmao":"on the floor laughing my ass off",
"otg":"on the ground",
"otgl":"on the ground laughing",
"oth":"off the hook",
"otl":"out to lunch",
"otoh":"on the other hand",
"otp":"on the phone",
"otp":"one true pairing",
"ots":"on the scene",
"ots":"off the subject",
"ots":"open two seater",
"ott":"over the top",
"otth":"on the third hand",
"ottomh":"off the top of my head",
"otw":"off to work",
"otw":"on the way",
"outta":"out of",
"ovie":"overlord",
"ownage":"completely owned",
"p/d":"per day",
"p/m":"per month",
"p/w":"password",
"p/w":"per week",
"p/y":"per year",
"p911":"parent alert!",
"p@h":"parents at home",
"pa":"parent alert",
"pad":"house",
"pah":"parents at home",
"pat":"patrol",
"paw":"parents are watching",
"pax":"peace and love",
"paye":"pay as you earn",
"payg":"pay as you go",
"pb&j":"peanut butter and jelly",
"pbe":"public beta environment",
"pbs":"public broadcasting service",
"pbuh":"peace be upon him",
"pc":"personal computer",
"pc":"politically correct",
"pc4pc":"picture comment for picture comment",
"pcid":"putting clothes in dryer",
"pcm":"please call me",
"pda":"public display of affection",
"pda":"personal digital assistant",
"pdh":"pretty darn hot",
"pdq":"pretty darn quick",
"pe":"physical education",
"pebcac":"problem exists between chair and computer",
"pebcak":"problem exists between chair and keyboard",
"pebkac":"problem exists between keyboard and chair",
"ped":"performance enhancing drug",
"peeps":"people",
"permabanned":"permanently banned",
"perv":"pervert",
"pf":"planetary fortress",
"pf":"preflop",
"pf":"pink floyd",
"pfa":"please find attached",
"pfo":"pissed and fell over",
"pfr":"preflop raise",
"pfr":"plasma, frag, rocket",
"pg":"pretty good",
"pgp":"preferred gender pronoun",
"phat":"pretty hot and tempting",
"phobar":"photoshopped beyond all recognition",
"pibkac":"problem is between keyboard and chair",
"pic":"picture",
"pimp":"peeing in my pants (laughing)",
"pio":"pass it on",
"piog":"posted in other groups",
"pir":"parent in room",
"pir":"people in room",
"pita":"pain in the ass",
"pix":"pictures",
"pj":"pearl jam",
"pjdwys":"personal joke, don't worry yourself",
"pjs":"pajamas",
"pk":"player kill",
"pkmn":"pokmon",
"pl":"pinkliner",
"pl":"pig latin",
"pl":"punch line",
"pl":"playlist",
"pl&":"planned",
"pl0x":"please",
"pl8":"plate",
"pld":"played",
"plj":"peace, love, joy",
"plmk":"please let me know",
"plos":"parents looking over shoulder",
"plox":"please",
"pls":"please",
"plz":"please",
"plzrd":"please read",
"pm":"private message",
"pm":"postmeridian",
"pm5k":"powerman 5000",
"pmd":"pokmon mystery dungeon",
"pmfji":"pardon me for jumping in",
"pmji":"pardon my jumping in",
"pmki":"pretty much killin' it",
"pmp":"peed my pants",
"pmpl":"piss my pants laughing",
"pmsl":"piss myself laughing",
"pmwof":"putting more wood on the fire",
"pnar":"poppin and a ranging",
"pnp":"plug and play",
"po-po":"police",
"poas":"pee on a stick",
"poc":"point of contact",
"poc":"proof of concept",
"poc":"piece of crap",
"poed":"pissed off",
"poms":"parents over my shoulder",
"poms":"peace out my sucka",
"pos":"piece of suck",
"pos":"parent over shoulder",
"pos":"power of suggestion",
"posbl":"possible",
"poser":"pretender",
"pot":"potion",
"pot":"marijuana",
"potb":"pat on the back",
"potc":"pirates of the caribbean",
"potc":"peck on the cheek",
"pothead":"person who smokes a lot of pot",
"poto":"phantom of the opera",
"potus":"president of the united states",
"pous":"president of the united states",
"pov":"point of view",
"pow":"prisoner of war",
"pp":"power points",
"pp":"personal problem",
"pp":"patterned paper",
"pp":"pause please",
"ppd":"postpartum depression",
"ppda":"parents pacing de area",
"ppl":"people",
"ppp":"peace",
"ppv":"pay-per-view",
"pr":"public relations",
"prancercise":"a prance-like exercise",
"presh":"precious",
"prl":"parents are listening",
"probs":"probably",
"proc":"programmed random occurrence",
"prof":"professor",
"prolly":"probably",
"promo":"promotion",
"props":"recognition",
"prot":"protection",
"prt":"partial retweet",
"prvt":"private",
"prw":"parents are watching",
"ps":"postscript",
"ps2":"playstation 2",
"ps3":"playstation 3",
"psa":"public service announcement",
"psog":"pure stroke of genius",
"psp":"playstation portable",
"pst":"please send tell",
"ptb":"powers that be",
"ptfo":"play the freaking objective",
"pth":"prime tanning hours",
"pti":"pardon the interruption",
"ptiypasi":"put that in your pipe and smoke it",
"ptl":"player to left",
"ptl":"praise the lord",
"ptm":"please tell me",
"pto":"pass this on",
"pto":"paid time off",
"ptoyed":"please turn off your electronic devices",
"ptr":"player to right",
"ptr":"public test realm",
"ptsb":"pass the sick bucket",
"pug":"pick up group",
"puk":"pin unlock key",
"puks":"pick up the kids",
"pusimp":"put yourself in my position",
"puter":"computer",
"pvc":"player versus computer",
"pve":"player versus environment",
"pvp":"player versus player",
"pvp":"protoss versus protoss",
"pvt":"protoss versus terran",
"pvt":"private",
"pvz":"protoss versus zerg",
"pw":"password",
"pwn":"own",
"pwn2own":"pwn to own contest",
"pwn3d":"owned",
"pwnage":"ownage",
"pwnd":"owned",
"pwned":"owned",
"pwnt":"owned",
"pwof":"putting wood on the fire",
"pwt":"poor white trash",
"pyhooya":"pull your head out of your ass",
"pysimp":"put yourself in my place",
"pyt":"pretty young thing",
"q4u":"question for you",
"qfe":"question for everyone",
"qfe":"quoted for emphasis",
"qft":"quoted for truth",
"qq":"quick question",
"qqn":"looking",
"qrg":"quick reference guide",
"qt":"cutie",
"qtpi":"cutie pie",
"abbreviation":"meaning",
"r":"are",
"r8":"rate",
"rad":"radical",
"ragequit":"angrily exiting",
"rak":"random act of kindness",
"rake":"poker site commission",
"ratm":"rage against the machine",
"rawr":"roar",
"rax":"barracks",
"rbay":"right back at you",
"rbr":"reverse buyer's remorse",
"rbtl":"read between the lines",
"rdf":"real deal feeling",
"rdnk":"redneck",
"rdps":"ranged damage per second",
"rdt":"relationship defining talk",
"rdy":"ready",
"re":"replay",
"re":"resident evil",
"re":"regarding",
"redneck":"uneducated southerner",
"ref":"referee",
"rehi":"hi again",
"rents":"parents",
"rep":"reputation",
"resq":"rescue",
"resto":"restoration",
"rez":"resurrection",
"rfc":"request for comment",
"rfp":"request for proposal",
"rgd":"regard",
"rgds":"regards",
"rhcp":"red hot chili peppers",
"rhip":"rank hath its privileges",
"rickroll":"to mislead someone",
"ridic":"ridiculous",
"rip":"rest in peace",
"rl":"real life",
"rlrt":"real life retweet",
"rly":"really",
"rm":"room",
"rma":"return merchandise authorization",
"rmah":"real money auction house",
"rml":"read my lips",
"rmp":"rogue, mage, priest",
"rn":"run",
"rn":"russian",
"rng":"random number generator",
"rnt":"aren't",
"robl":"rolling on back laughing",
"robo":"robotics facility",
"rof":"rolling on floor",
"rofl":"rolling over freakin' laughing",
"rofl":"rolling on the floor laughing",
"roflmao":"rolling on floor, laughing my ass off",
"roflmaoqwerty":"rolling on floor laughing my ass off at the keyboard",
"roflmaowec":"rolling on floor laughing my ass off while eating cookie",
"roflmbwao":"rolling on floor laughing my big white ass off",
"roflmfao":"rolling on the floor laughing my freakin' ass off",
"roflmro":"rolling on the floor laughing my rear off",
"roflol":"rolling on the floor laughing out loud",
"rofltrabtd":"rolling on floor laughing, thinking republicans are better than democrats",
"roflusa":"rolling on floor laughing until sides ache",
"rolf":"rolling on laughing floor",
"rollout":"to leave",
"rolmbo":"rolling over laughing my butt off",
"rom":"emulator game",
"rom":"rough order of magnitude",
"rotf":"rolling on the floor",
"rotffl":"rolling on the freaking floor laughing",
"rotfl":"rolling on the floor laughing",
"rotflh":"rolling on the floor laughing hysterically",
"rotflmao":"rolling on the floor laughing my ass off",
"rotflmbo":"rolling on the floor, laughing my behind off",
"rotflmfao":"rolling on the floor laughing my fat ass off",
"rotflmfao":"rolling on the floor laughing my fucking ass off",
"rotflol":"rolling on the floor laughing out loud",
"rots":"right on the spot",
"rous":"rodents of unusual size",
"rox":"rocks",
"roxorz":"rocks",
"rp":"role play",
"rpc":"role play chat",
"rpg":"role playing game",
"rpmo":"really pissing me off",
"rq":"real quick",
"rsn":"real soon now",
"rsvp":"rpondez s'il vous plat",
"rt":"retweet",
"rt":"real-time",
"rtb":"real-time bidding",
"rtf":"return the favor",
"rtfa":"read the flippin' article",
"rtfb":"read the flippin' book",
"rtffaq":"read the flippin' faq",
"rtfm":"read the flippin' manual",
"rtfmm":"read the flippin' manual, moron",
"rtfs":"read the flippin' source",
"rthx":"retweet thanks",
"rti":"real-time interruption",
"rts":"real-time strategy",
"ru":"are you",
"rub":"are you back",
"ruc":"are you coming?",
"rucb":"are you coming back?",
"rucmng":"are you coming?",
"rufr":"are you for real",
"rumof":"are you male or female?",
"ruok":"are you ok?",
"rus":"are you serious?",
"rusos":"are you stupid or something?",
"rut":"are you there?",
"rw":"real world",
"rwa":"ready, willing, and able",
"rx":"prescription",
"ryc":"regarding your comment",
"ryfs":"are you freakin' serious?",
"s/o":"sold out",
"s/u":"shut up",
"s/w":"software",
"s2r":"send to receive",
"s2s":"sorry to say",
"s2u":"same to you",
"sack":"bed",
"sae":"stamped addressed envelope",
"sahd":"stay-at-home dad",
"sahm":"stay-at-home mom",
"sahp":"stay-at-home parent",
"sal":"such a laugh",
"salab":"stop acting like a baby",
"salts":"smiled a little then stopped",
"salty":"upset",
"samagal":"stop annoying me and get a life",
"samzd":"still amazed",
"sase":"self-addressed stamped envelope",
"sat":"scholastic aptitude test",
"sat":"sorry about that",
"sb":"smiling back",
"sbt":"sorry 'bout that",
"sbtm":"should be there momentarily",
"sbux":"starbucks",
"sc2":"starcraft 2",
"sc2nite":"starcraft 2 tonight?",
"scarjo":"scarlett johansson",
"sched":"schedule",
"scnr":"sorry, could not resist",
"scrilla":"money",
"scrub":"loser",
"sd":"sweet dreams",
"sdihtt":"someday i'll have the time",
"seal":"slaying everyone and laughing",
"sec":"second",
"selfie":"picture of yourself",
"seltering":"to stick out your rear in a fitness pose",
"senioritis":"senior laziness",
"seo":"search engine optimization",
"serp":"search engine results page",
"sesh":"session",
"sete":"smiling ear to ear",
"sf":"science fiction",
"sfb":"suck for brains",
"sff":"so freaking funny",
"sfs":"sorry for spam",
"sftif2lolblimh":"so funny that i forgot to laugh out loud but laughed in my head",
"sfx":"special effects",
"sfy":"speak for yourself",
"sg":"sounds good",
"sh":"short handed",
"sh":"same here",
"shady":"sly",
"shaft":"ripped off",
"shat":"shattrath city",
"shatt":"shattrath city",
"shawtie":"fine female",
"shawty":"fine female",
"shid":"slaps head in disgust",
"shmily":"see how much i love you?",
"shmup":"shoot 'em up",
"sho":"sure",
"shortie":"fine female",
"shorty":"fine female",
"shucks":"expression of disappointment",
"shud":"should",
"sh^":"shut up",
"sia":"someone is around",
"sic":"spelling incorrect",
"sig":"silence is golden",
"sil":"sister-in-law",
"sil":"son-in-law",
"sim":"shoot, it's monday",
"sinbad":"single income, no boyfriend, absolutely desperate",
"sit":"stay in touch",
"sitch":"situation",
"sitd":"still in the dark",
"sitrep":"situation report",
"siul8r":"see you later",
"siv":"bad goaltender",
"sk8":"skate",
"sk8r":"skater",
"skelly":"skeleton",
"skytoss":"protoss air units",
"slammin":"awesome",
"slm":"socially limiting maneuver",
"sly":"still love you",
"smdh":"shaking my dick head",
"sme":"subject matter expert",
"smem":"send me an e-mail",
"smexy":"smart and sexy",
"smf":"so much fun",
"smfh":"shaking my flippin' head",
"smh":"shaking my head",
"smh":"smash my head",
"smh":"scratching my head",
"smishing":"sms phishing",
"sml":"so much love",
"smooch":"kiss",
"smp":"survival multiplayer",
"sms":"short message service",
"smtw":"sunday, monday, tuesday, wednesday",
"smun":"send me your number",
"smurf":"hidden alternate character",
"sn":"screen name",
"snafu":"situation normal, all fouled up",
"snap":"shoot!",
"snert":"snot nosed egotistical rude teenager",
"snes":"super nintendo entertainment system",
"sng":"sit 'n go",
"snmp":"so not my problem",
"so8":"sweet",
"soa":"sons of anarchy",
"soab":"son of a bitch",
"soad":"system of a down",
"soaps":"soap operas",
"sob":"son of a bitch",
"softie":"a sentimental person",
"soh":"sense of humor",
"soh":"slight of hand",
"sohf":"sense of humor failure",
"sok":"it's ok",
"sol":"suck out of luck",
"somepony":"somebody",
"somy":"sick of me yet?",
"soof":"swear on our friendship",
"sooi":"stay out of it",
"sop":"standard operating procedure",
"sorta":"sort of",
"sos":"someone over shoulder",
"sos":"save our souls",
"sos":"same old stuff",
"sos":"someone special",
"sosg":"someone over shoulder gone",
"soso":"same old, same old",
"sota":"state of the art",
"sotu":"state of the union",
"sow":"speaking of which",
"soz":"i'm sorry",
"sp":"spelling",
"sp":"spell power",
"spd":"sensory processing disorder",
"spd":"symphysis pubis dysfunction",
"spd":"spinning piledriver",
"spec":"specialization",
"speedling":"zergling with metabolic boost",
"spim":"im spam",
"spit":"freestyle rap",
"spit":"flirt",
"spk":"speak",
"spkr":"speaker",
"spleef":"minecraft multiplayer game",
"sppu":"sold pending pickup",
"spros":"stop, parents reading over shoulder",
"spst":"same place, same time",
"squidward":"villager",
"sro":"standing room only",
"srry":"sorry",
"srs":"serious",
"srsly":"seriously",
"sry":"sorry",
"ss":"screenshot",
"ssa":"same sex attraction",
"ssd":"solid state drive",
"ssdd":"same stuff, different day",
"ssia":"subject says it all",
"ssl":"secure sockets layer",
"ssp":"survival single player",
"st2m":"stop talking to me",
"stache":"mustache",
"stahp":"stop",
"star":"stop, think, act, review",
"stats":"statistics",
"stby":"sucks to be you",
"stfd":"sit the fuck down",
"stfd":"shut the front door",
"stfu":"shut the fuck up",
"stfw":"search the flippin' web",
"sthu":"shut the heck up",
"stlsdr":"still too long, still didn't read",
"stms":"sick to my stomach",
"stoked":"excited",
"stp":"stone temple pilots",
"stpd":"stupid",
"str":"strength",
"str8":"straight",
"stt":"single table tournament",
"stth":"speak to the hand",
"sttw":"sabrina the teenage witch",
"stud":"attractive male",
"stud":"highly skilled individual",
"stw":"search the web",
"su":"shut up",
"suafu":"situation unchanged, all fouled up",
"subs":"subwoofers",
"suf":"shut your face",
"sum1":"someone",
"sup":"what's up",
"supes":"super",
"susfu":"situation unchanged, still fouled up",
"sux":"sucks",
"sw":"software",
"swa":"so what ass",
"swag":"free stuff",
"swak":"sealed with a kiss",
"swalk":"sealed with a loving kiss",
"swalk":"sweet, with all love, kisses",
"swammie":"firearm",
"swas":"said with a smile",
"swatting":"to create a false emergency",
"swdywtta":"so what do you want to talk about",
"swl":"screaming with laughter",
"swmbo":"she who must be obeyed",
"swoll":"muscular",
"swot":"dedicated student",
"swtor":"star wars: the old republic",
"swyp":"so what's your problem",
"sy":"sincerely yours",
"syih":"see you in hell",
"syl":"see you later",
"syla":"see you later alligator",
"sync":"synchronize",
"sys":"see you soon",
"sysadmin":"system administrator",
"sysop":"system operator (chat monitor)",
"syt":"see you tomorrow",
"sytycd":"so you think you can dance",
"syy":"shut your yapper",
"t1d":"type 1 diabetes",
"t2go":"time to go",
"t2m":"talk to me",
"t2u":"talk to you",
"t2ul":"talk to you later",
"t2ul8er":"talk to you later",
"t2ul8r":"talk to you later",
"t4lmk":"thanks for letting me know",
"t4p":"thanks for posting",
"t4t":"thanks for trade",
"ta":"thanks again",
"ta":"teaching assistant",
"taahm":"two and a half men",
"tab":"talking about",
"tac":"that ain't cool",
"tacky":"bad taste",
"tada":"announcement",
"tafn":"that's all for now",
"tank":"strong character",
"tanstaafl":"there ain't no such thing as a free lunch",
"tard":"retard",
"tarfu":"things are really foobarred up",
"tarfu":"things are really fouled up",
"tat":"this and that",
"tat":"tattoo",
"tau":"thinking about you",
"tawog":"the amazing world of gumball",
"tay":"thinking about you",
"tb":"terabyte",
"tba":"to be announced",
"tbc":"to be continued",
"tbcl":"to be continued later",
"tbd":"to be determined",
"tbe":"to be edited",
"tbf":"to be frank",
"tbf":"to be fair",
"tbfu":"too bad for you",
"tbh":"to be honest",
"tbqh":"to be quite honest",
"tbr":"to be released",
"tbr":"to be read",
"tbr":"to be resolved",
"tbr":"to be revised",
"tbt":"throwback thursday",
"tbt":"truth be told",
"tbtg":"thanks be to god",
"tby":"teacher behind you",
"tc":"take care",
"tcb":"taking care of business",
"tccic":"take care 'cause i care",
"tcfn":"take care for now",
"tcg":"trading card game",
"tco":"taken care of",
"tcob":"takin' care of business",
"tcood":"taking clothes out of dryer",
"tcwb":"take care, write back",
"td":"touchdown",
"tdl":"the do lab",
"tdm":"team death match",
"tdswjs":"the daily show with jon stewart",
"tdtm":"talk dirty to me",
"tebowing":"to get in a position of praying with one knee on the ground",
"tech":"technology",
"teemo":"teenage emo",
"teemo":"the swift scout",
"teh":"the",
"tel":"telephone",
"teme":"tell me",
"terribad":"terrible bad",
"tf":"twisted fate",
"tf2":"team fortress 2",
"tfb":"too freakin' bad",
"tff":"too freakin' funny",
"tff":"twitter follower-friend",
"tfk":"thousand foot krutch",
"tflmk":"thanks for letting me know",
"tfta":"thanks for the add",
"tfti":"thanks for the information",
"tg":"thank goodness",
"tgff":"thank god for friday",
"tgif":"thank goodness it's friday",
"th":"tears of happiness",
"thang":"thing",
"thanksgivukkah":"thanksgiving and hanukkah",
"thanq":"thank you",
"thar":"there",
"thkq":"thank you",
"thnq":"thank you",
"tho":"though",
"thru":"through",
"tht":"that",
"thth":"too hot to handle",
"thx":"thanks",
"tia":"thanks in advance",
"tic":"tongue in cheek",
"til":"today i learned",
"tilted":"aggravated",
"tips":"to improve professional service",
"tisnf":"that is so not fair",
"tisu":"this is so unfair",
"titf":"that is too funny",
"tix":"tickets",
"tji":"try joining in",
"tka":"totally kick ass",
"tl":"tell",
"tla":"three letter acronym",
"tlc":"tender love and care",
"tldr":"too long, didn't read",
"tlk":"talk",
"tlkin":"talking",
"tlking":"talking",
"tltr":"too long to read",
"tm":"trademark",
"tm":"trouble maker",
"tm":"tickle me",
"tm":"tell me",
"tma":"take my advice",
"tmai":"tell me about it",
"tmb":"tag me back",
"tmb":"text me back",
"tmdf":"to my dearest friend",
"tmft":"too much free time",
"tmg":"that's my girl",
"tmi":"too much information",
"tmnt":"teenage mutant ninja turtles",
"tmrw":"tomorrow",
"tmsf":"too much science fiction",
"tmth":"too much too handle",
"tng":"the next generation",
"tnt":"till next time",
"tnx":"thanks",
"toc":"table of contents",
"tod":"truth or dare",
"toh":"the other half",
"toh":"typing one-handed",
"toiom":"this one is on me",
"tol":"thinking of laughing",
"tomoz":"tomorrow",
"toodles":"goodbye",
"toon":"alternate character",
"tootles":"goodbye",
"tootsies":"toes",
"tos":"the original series",
"totes":"totally",
"tots":"totally",
"tots":"tater tots",
"tou":"thinking of you",
"tourney":"tournament",
"towl":"the one with love",
"townie":"lifelong resident of one town",
"tpk":"total party kill",
"tpm":"tweets per minute",
"tpt":"trailer park trash",
"tptb":"the powers that be",
"tpvpz":"terran protoss versus protoss zerg",
"tq":"thank you",
"tqvm":"thank you very much",
"travoltafied":"to mispronounce a name",
"travoltafy":"to mispronounce a name",
"travoltified":"to mispronounce a name",
"travoltify":"to mispronounce a name",
"trbl":"terrible",
"trdmf":"tears running down my face",
"trekker":"star trek fan",
"trekkie":"star trek fan",
"trolol":"laughing at troll",
"trs":"that really sucks",
"tru":"true",
"tru":"dat true that",
"ts":"tough stuff",
"tsfh":"two steps from hell",
"tsnf":"that's so not fair",
"tss":"toxic shock syndrome",
"tss":"this stuff sucks",
"tstl":"too stupid to live",
"tt":"trending topic",
"tt":"talking to",
"tt2t":"too tired to talk",
"tt4n":"ta-ta for now",
"ttbomk":"to the best of my knowledge",
"ttfn":"ta-ta for now",
"ttg":"time to go",
"ttka":"time to kick ass",
"ttl":"time to live",
"ttl":"talk to you later",
"ttl":"time to leave",
"ttly":"totally",
"ttm":"talk to me",
"ttmn":"talk to me now",
"ttt":"to the top",
"ttte":"thomas the tank engine",
"tttt":"to tell the truth",
"ttul":"talk to you later",
"tty":"talk to you",
"ttyaw":"talk to you after work",
"ttyiab":"talk to you in a bit",
"ttyiam":"talk to you in a minute",
"ttyl":"talk to you later",
"ttylmf":"talk to you later, my friend",
"ttylxox":"talk to you later, hugs and kisses",
"ttyn":"talk to you never",
"ttyootd":"talk to you one of these days",
"ttys":"talk to you soon",
"ttyt":"talk to you tomorrow",
"ttyvs":"talk to you very soon",
"ttyw":"talk to you whenever",
"tu":"thank you",
"tude":"attitude",
"tui":"turning you in",
"turf":"neighborhood",
"turtling":"playing defensively",
"tut":"totally unique thought",
"tvp":"terran versus protoss",
"tvt":"terran versus terran",
"tvz":"terran versus zerg",
"twaddict":"twitter addict",
"twd":"the walking dead",
"twds":"towards",
"tweavesdropping":"eavesdropping on twitter",
"tweeple":"twitter people",
"tweeps":"twitter peeps",
"tweetsult":"insulting tweet",
"twerk":"hip-gyrating dance move",
"twerking":"shaking hips in a bouncing motion",
"twewbie":"twitter newbie",
"twhs":"that's what he said",
"twimc":"to whom it may concern",
"twink":"powerful low-level character",
"twis":"that's what i said",
"twit":"that's what i thought",
"twitch":"video game streaming website",
"twma":"till we meet again",
"tws":"this website sucks",
"twsi":"that was so ironic",
"twss":"that's what she said",
"twti":"that was totally ironic",
"tx":"thanks",
"txt":"text",
"txtin":"texting",
"ty":"thank you",
"tyfa":"thank you for asking",
"tyl":"thank you lord",
"tym":"thank you much",
"tyt":"take your time",
"tyvm":"thank you very much",
"u":"you",
"u-ok":"you ok?",
"u/l":"upload",
"u2":"you too",
"u2u":"up to you",
"uber":"the best",
"uce":"unsolicited commercial e-mail",
"udfi":"you don't fit in",
"ug2bk":"you got to be kidding",
"ugh":"disgusted",
"ui":"user interface",
"ukwis":"you know what i'm saying",
"ul":"unlucky",
"ul":"upload",
"ulkgr8":"you look great",
"ulpp":"unluckiest person on the planet",
"ult":"ultimate ability",
"unadr":"you need a doctor",
"undies":"underwear",
"unfriend":"remove facebook friend",
"uno":"you know",
"uok":"you ok?",
"uome":"you owe me",
"ups":"jumping ability",
"ur":"you are",
"ur":"your",
"ur2m":"you are too much",
"ura":"you're a",
"ura*":"you are a star",
"urab":"you are a bitch",
"ural":"you are a loser",
"uraqt":"you are a cutie",
"urc":"you are caught",
"ure":"you're",
"urgr8":"you are great",
"url":"uniform resource locator",
"urp":"vomit",
"urs4e":"yours forever",
"ursktm":"you are so kind to me",
"urtb":"you are the best",
"urw":"you're welcome",
"usa":"united states of america",
"usad":"you're such a dork",
"usb":"you sexy bitch",
"ut":"you there?",
"utg":"under the gun",
"uw":"you're welcome",
"ux":"user interface",
"uy":"up yours",
"vacay":"vacation",
"vbg":"very big grin",
"vbs":"very big smile",
"vc":"voice chat",
"ve":"very emotional",
"veg":"do nothing",
"veggies":"vegetables",
"vet":"veterinarian",
"vet":"veteran",
"vfx":"visual effects",
"vg":"video game",
"vg":"very good",
"vgc":"very good condition",
"vibe":"atmosphere",
"vid":"video",
"vip":"very important person",
"vlog":"video blog",
"vlogger":"video blogger",
"vm":"voicemail",
"vn":"very nice",
"vnh":"very nice hand",
"vod":"video on demand",
"vpip":"voluntary put in pot",
"vr":"virtual reality",
"vry":"very",
"vs":"versus",
"vsc":"very soft chuckle",
"vvs":"vertical video syndrome",
"w/":"with",
"w/b":"welcome back",
"w/e":"whatever",
"w/o":"without",
"w00t":"yay",
"w00t":"joy and excitement",
"w2f":"way too funny",
"w2g":"way to go",
"w2k":"windows 2000",
"w4u":"wait for you",
"w8":"wait",
"w84m":"wait for me",
"w8am":"wait a minute",
"w8ing":"waiting",
"w8n":"waiting",
"wa":"what",
"waa":"crying",
"wack":"strange",
"waditwb":"we always did it that way before",
"wadr":"with all due respect",
"waefrd":"when all else fails, read directions",
"waggro":"wife aggro",
"wags":"wife and girlfriends",
"wah":"work at home",
"wahm":"work at home mom",
"wail":"awesome",
"wam":"wait a minute",
"wan2":"want to",
"wannabe":"want to be",
"wat":"what",
"watev":"whatever",
"watevs":"whatever",
"wayd":"what are you doing",
"waydrn":"what are you doing right now",
"waydt":"what are you doing tonight",
"wb":"welcome back",
"wbp":"write back please",
"wbs":"write back soon",
"wbu":"what about you",
"wbw":"with best wishes",
"wbwyc":"write back when you can",
"wby":"what about you?",
"wc":"who cares",
"wc":"water closet",
"wcg":"world cyber games",
"wcm":"warcraft movies",
"wcm":"web content management",
"wcms":"web content management system",
"wcs":"starcraft ii world championship series",
"wcw":"woman-crush wednesday",
"wd":"well done",
"wdit":"why do i try",
"wdmb":"will do my best",
"wdtfs":"what does the fox say?",
"wdumbt":"what do you mean by that?",
"wduw":"what do you want",
"wdym":"what do you mean?",
"wdymbt":"what do you mean by that?",
"wdyt":"what do you think",
"webpany":"web company",
"wee":"expression of excitement",
"weed":"marijuana",
"weg":"wicked evil grin",
"wei":"whatever idiot",
"welp":"well",
"weml":"whatever major loser",
"weu":"what's eating you?",
"weva":"whatever",
"wewt":"woot",
"wfm":"works for me",
"wg":"wintergrasp",
"wha":"what",
"whaling":"acting like a breaching whale",
"whatevs":"whatever",
"whew":"expression of relief",
"whip":"vehicle",
"whipped":"tired",
"whiz":"smart person",
"whoa":"expression of surprise",
"whomp":"low hitting sound",
"wht":"what",
"whu":"warcraft hunters union",
"whybad":"where have you been all day",
"whybatt":"where have you been all this time",
"wicked":"very cool",
"wiifm":"what's in it for me?",
"wipe":"total death",
"witr":"who's in the room",
"witww":"what in the wide world",
"wiyp":"what is your problem",
"wk":"week",
"wkd":"wicked",
"wknd":"weekend",
"wl":"whatta loser",
"wld":"would",
"wlk":"walk",
"wlol":"whip laugh out loud",
"wlyk":"will let you know",
"wmao":"working my ass off",
"wmb":"write me back",
"wn":"why not",
"wnditwb":"we never did it this way before",
"woa":"work of art",
"woah":"expression of surprise",
"wohm":"working outside home mom",
"wol":"wings of liberty",
"wombat":"waste of money, brains, and talent",
"wonky":"weird",
"woot":"waste of our time",
"wos":"wife over shoulder",
"wot":"waste of time",
"wot":"what",
"wotd":"workout of the day",
"wotlk":"wrath of the lich king",
"wow":"world of warcraft",
"wowzer":"wow",
"wowzerz":"wow",
"woz":"worry",
"wp":"wordpress",
"wp":"well played",
"wp":"wrong person",
"wpm":"words per minute",
"wpt":"world poker tour",
"wr":"win ratio",
"wrisit":"where is it",
"wrt":"with regard to",
"wrt":"with respect to",
"wru":"where are you",
"wru@":"where are you at?",
"wrud":"what are you doing",
"wrudoin":"what are you doing?",
"wsop":"world series of poker",
"wsp":"whisper",
"wt":"what the",
"wta":"women tell all",
"wta":"winner takes all",
"wtb":"want to buy",
"wtbh":"what the bloody hell",
"wtc":"what the crap",
"wtf":"what the fuck",
"wtfay":"where the fuck are you?",
"wtfe":"what the frick ever",
"wtfnf":"what the fucking fuck",
"wtfo":"what the fuck; over",
"wtfru":"where the fuck are you?",
"wtg":"way to go",
"wtgp":"want to go private",
"wth":"what the heck",
"wthdtm":"what the heck does that mean?",
"wthwt":"what the heck was that?",
"wtmi":"way too much information",
"wts":"want to sell",
"wts":"what the suck",
"wtt":"want to trade",
"wtv":"whatever",
"wtyaf":"who threw you a fish?",
"wu":"what's up",
"wua":"what's up anyway?",
"wub":"love",
"wubu2":"what have you been up to",
"wud":"what are you doing",
"wud":"what's up, dog?",
"wuf":"wow, you're funny",
"wuf":"where you from?",
"wugf":"what up girlfriend",
"wuh":"what",
"wuigb":"wait until i get back",
"wup":"what's up?",
"wuss":"wimp",
"wut":"what",
"wuu2":"what are you up to",
"wuwt":"what's up with that",
"wuz":"was",
"wv":"with",
"ww":"well won",
"ww":"wrong way",
"ww":"wrong window",
"wwe":"world wrestling entertainment",
"wwf":"world wrestling federation",
"wwf":"world wildlife fund",
"wwi":"what was it",
"wwjd":"what would jesus do",
"wwtfw":"what's with this f'd up world",
"wwwf":"world wide wrestling federation",
"wya":"where you at?",
"wyb":"watch your back",
"wyb":"when you buy",
"wyd":"who's your daddy?",
"wyd":"what you doing?",
"wygowm":"will you go out with me",
"wymm":"will you marry me?",
"wysiwyg":"what you see is what you get",
"wywh":"wish you were here",
"w^":"what's up",
"x":"kiss",
"xb":"xbox",
"xbf":"ex-boyfriend",
"xbl":"xbox live",
"xc":"cross country",
"xd":"laughing out loud",
"xdd":"laughing especially hard",
"xep":"except",
"xfer":"transfer",
"xgf":"ex-girlfriend",
"xit":"exit",
"xitb4ili":"exit before i lose it",
"xlnt":"excellent",
"xmute":"transmute",
"xo":"kiss and hug",
"xox":"kiss, hug, kiss",
"xoxo":"hugs and kisses",
"xp":"experience",
"xt":"cross training",
"xtl":"cross the line",
"xx":"kisses",
"xyz":"examine your zipper",
"y":"why",
"y/r":"yeah right",
"y2k":"you're too kind",
"ya":"you",
"ya":"yes",
"yaa":"yet another acronym",
"yaba":"yet another bloody acronym",
"yada":"blah blah",
"yall":"you all",
"yarr":"angry pirate sound",
"yatb":"you are the best",
"yayo":"cocaine",
"ybs":"you'll be sorry",
"ybysa":"you bet your sweet ass",
"yccoi":"you can count on it",
"yd":"ya dig?",
"yd":"yes dear",
"ydg":"ya dig",
"ydi":"you deserved it",
"yeap":"yes",
"yep":"yes",
"yepperz":"yes",
"yer":"your",
"yesh":"yes",
"yf":"you fail",
"yg2bj":"you've got to be joking",
"ygg":"you go girl",
"ygm":"you've got mail",
"ygti":"you get the idea",
"yhbt":"you have been trolled",
"yhm":"you have mail",
"yhs":"your hand sucks",
"yim":"yahoo! instant messenger",
"yk":"you're kidding",
"ykhii":"you know how it is",
"yki":"you know it",
"ykw":"you know what",
"ym":"your mom",
"ymbj":"you must be joking",
"ymmd":"you made my day",
"ymmv":"your mileage may vary",
"ymsf":"your momma's so fat",
"yo":"hi",
"yolo":"you only live once",
"yomank":"you owe me a new keyboard",
"yoow":"you're out of work",
"yoyo":"you're on your own",
"ypml":"you're pulling my leg",
"yr":"yeah, right",
"yr":"your",
"yrag":"you are a geek",
"yrg":"you are good",
"yrl":"you are lame",
"yrp":"europe",
"yrs":"years",
"ys":"you suck",
"ys":"yours sincerely",
"ysj":"you're so jealin",
"yst":"you still there",
"ysw":"yeah sure whatever",
"yt":"you there?",
"yt?":"you there?",
"ytd":"year-to-date",
"ytf":"why the fuck",
"yup":"yes",
"yupz":"ok",
"yvw":"you're very welcome",
"yw":"you're welcome",
"ywa":"you're welcome anyway",
"ywia":"you're welcome in advance",
"yyss":"yeah yeah, sure sure",
"yyssw":"yeah yeah, sure sure, whatever",
"z":"zero",
"zing":"owned",
"zomfg":"oh my freakin' gosh!",
"zomg":"oh my gosh!",
"zoning":"constraining enemy positions",
"zvp":"zerg versus protoss",
"zvt":"zerg versus terran",
"zvz":"zerg versus zerg",
"zzz":"sleeping",
}